# MAMA-MIA data exploration and download

In [1]:
%cd ../..

/home/bhkuser/bhklab/katy/jarvais-breast

In [2]:
import pandas as pd
from damply import dirs 
from pathlib import Path

In [3]:
dataset = "BCN-AIM_MAMA-MIA"

In [4]:
clinical_data = pd.read_excel(dirs.RAWDATA / dataset / "clinical/clinical_and_imaging_info.xlsx")
clinical_data = clinical_data.set_index(keys=['patient_id'])

In [5]:
# Filter by data with non-NA values for PCR, HR and HER2
features_to_pred = clinical_data.filter(items=['pcr', 'hr', 'her2'])
features_to_pred

            pcr   hr  her2
patient_id
DUKE_001    0.0  0.0   1.0
DUKE_002    0.0  0.0   0.0
DUKE_005    1.0  1.0   1.0
DUKE_009    1.0  0.0   0.0
DUKE_010    0.0  0.0   0.0
...         ...  ...   ...
NACT_64     0.0  NaN   NaN
NACT_65     0.0  1.0   0.0
NACT_66     0.0  1.0   1.0
NACT_67     0.0  0.0   0.0
NACT_68     0.0  1.0   1.0

[1506 rows x 3 columns]

In [6]:
nona_pcr = features_to_pred.dropna(subset='pcr')
nona_hr = features_to_pred.dropna(subset='hr')
nona_her2 = features_to_pred.dropna(subset='her2')

print("PCR count:", len(nona_pcr))
print("HR count:", len(nona_hr))
print("HER2 count:", len(nona_her2))

PCR count: 1491
HR count: 1490
HER2 count: 1484

In [7]:
nona_pcr.dropna(subset=['hr', 'her2'])

            pcr   hr  her2
patient_id
DUKE_001    0.0  0.0   1.0
DUKE_002    0.0  0.0   0.0
DUKE_005    1.0  1.0   1.0
DUKE_009    1.0  0.0   0.0
DUKE_010    0.0  0.0   0.0
...         ...  ...   ...
NACT_63     0.0  1.0   1.0
NACT_65     0.0  1.0   0.0
NACT_66     0.0  1.0   1.0
NACT_67     0.0  0.0   0.0
NACT_68     0.0  1.0   1.0

[1469 rows x 3 columns]

# Download MAMA-MIA from Synapse

In [12]:
from synapseclient import Synapse, File
from synapseclient.operations import get
from synapseclient.models import Project, Folder
from synapseutils.sync import syncFromSynapse, generateManifest, generate_sync_manifest
from synapseutils.walk_functions import walk

In [ ]:
syn = Synapse()
syn.login()

image_dir_id = "syn64871114"
duke1_id = "syn64883023"

walk_results = walk(syn, image_dir_id, includeTypes=['file'])

# list(walk_results)

for dirpath, dirnames, filenames in walk_results:
    
    for sample in filenames:
        file_id = str(sample[0])
        if file_id.endswith('0000.nii.gz'):
            # print(sample)
            patient_id = file_id.removesuffix('_0000.nii.gz')
            out_path = dirs.RAWDATA / dataset / "images/scans" / patient_id

            syn_id = sample[1]
            syncFromSynapse(syn, entity=syn_id, path=out_path, ifcollision='keep.local', manifest='root')

# generateManifest(image_dir_id, allFiles filename=dirs.RAWDATA / dataset / "metadata/images_manifest.tsv")

Welcome, kscott! You are using the 'default' profile.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883026]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_001/DUKE_001_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880844]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_002/DUKE_002_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877589]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_005/DUKE_005_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871909]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_009/DUKE_009_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873045]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_010/DUKE_010_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879738]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_012/DUKE_012_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882179]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_019/DUKE_019_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879170]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_021/DUKE_021_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873832]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_022/DUKE_022_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883660]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_028/DUKE_028_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876129]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_032/DUKE_032_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879734]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_034/DUKE_034_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873236]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_040/DUKE_040_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880123]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_041/DUKE_041_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872331]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_043/DUKE_043_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877580]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_044/DUKE_044_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875977]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_045/DUKE_045_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883003]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_046/DUKE_046_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883623]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_048/DUKE_048_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876972]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_051/DUKE_051_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872489]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_055/DUKE_055_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872000]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_057/DUKE_057_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880451]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_059/DUKE_059_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878332]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_060/DUKE_060_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881577]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_061/DUKE_061_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882882]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_064/DUKE_064_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877097]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_069/DUKE_069_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878975]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_071/DUKE_071_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883902]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_077/DUKE_077_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881412]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_082/DUKE_082_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880859]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_086/DUKE_086_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879917]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_090/DUKE_090_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878970]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_091/DUKE_091_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876109]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_097/DUKE_097_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879645]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_099/DUKE_099_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874598]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_101/DUKE_101_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874429]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_103/DUKE_103_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880546]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_104/DUKE_104_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879694]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_105/DUKE_105_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882840]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_107/DUKE_107_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874548]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_114/DUKE_114_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878117]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_115/DUKE_115_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878270]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_116/DUKE_116_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881575]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_117/DUKE_117_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881610]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_119/DUKE_119_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883801]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_120/DUKE_120_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874469]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_123/DUKE_123_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882243]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_129/DUKE_129_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873177]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_132/DUKE_132_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878048]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_134/DUKE_134_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873432]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_136/DUKE_136_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872360]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_137/DUKE_137_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880834]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_141/DUKE_141_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880523]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_142/DUKE_142_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872079]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_144/DUKE_144_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880964]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_148/DUKE_148_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871124]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_150/DUKE_150_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880640]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_156/DUKE_156_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880214]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_157/DUKE_157_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879860]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_160/DUKE_160_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880709]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_163/DUKE_163_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878895]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_167/DUKE_167_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883826]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_168/DUKE_168_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880026]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_176/DUKE_176_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874912]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_177/DUKE_177_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882732]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_178/DUKE_178_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883304]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_180/DUKE_180_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881455]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_183/DUKE_183_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882361]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_185/DUKE_185_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876467]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_189/DUKE_189_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878345]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_192/DUKE_192_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876211]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_198/DUKE_198_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873782]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_202/DUKE_202_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879728]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_205/DUKE_205_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879357]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_211/DUKE_211_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871933]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_217/DUKE_217_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880314]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_218/DUKE_218_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873536]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_225/DUKE_225_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875166]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_228/DUKE_228_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871159]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_233/DUKE_233_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883351]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_234/DUKE_234_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875500]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_236/DUKE_236_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883396]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_237/DUKE_237_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882931]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_239/DUKE_239_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881479]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_240/DUKE_240_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874447]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_244/DUKE_244_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876984]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_250/DUKE_250_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879484]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_253/DUKE_253_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875571]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_255/DUKE_255_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881323]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_256/DUKE_256_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878949]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_258/DUKE_258_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875468]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_260/DUKE_260_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878614]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_265/DUKE_265_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871237]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_268/DUKE_268_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881603]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_269/DUKE_269_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882671]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_271/DUKE_271_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871423]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_275/DUKE_275_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880620]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_282/DUKE_282_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875965]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_283/DUKE_283_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881616]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_285/DUKE_285_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873863]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_287/DUKE_287_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875512]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_290/DUKE_290_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875629]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_293/DUKE_293_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877780]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_298/DUKE_298_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882318]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_301/DUKE_301_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871751]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_303/DUKE_303_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873921]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_304/DUKE_304_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871390]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_306/DUKE_306_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882395]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_307/DUKE_307_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881414]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_313/DUKE_313_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879244]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_317/DUKE_317_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882601]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_321/DUKE_321_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872856]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_323/DUKE_323_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879777]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_328/DUKE_328_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878839]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_333/DUKE_333_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872516]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_335/DUKE_335_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882184]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_338/DUKE_338_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882067]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_345/DUKE_345_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878276]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_346/DUKE_346_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879105]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_350/DUKE_350_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881951]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_353/DUKE_353_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873490]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_356/DUKE_356_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877995]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_360/DUKE_360_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882131]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_363/DUKE_363_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881895]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_368/DUKE_368_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878564]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_377/DUKE_377_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878205]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_378/DUKE_378_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877984]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_383/DUKE_383_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876047]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_385/DUKE_385_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874210]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_386/DUKE_386_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876723]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_387/DUKE_387_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882446]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_395/DUKE_395_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881100]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_397/DUKE_397_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879552]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_398/DUKE_398_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883289]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_399/DUKE_399_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883761]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_400/DUKE_400_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880185]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_406/DUKE_406_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881474]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_407/DUKE_407_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880832]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_408/DUKE_408_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876916]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_412/DUKE_412_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871310]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_414/DUKE_414_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873132]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_420/DUKE_420_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878541]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_424/DUKE_424_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879558]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_428/DUKE_428_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883104]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_429/DUKE_429_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881749]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_431/DUKE_431_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873754]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_435/DUKE_435_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872449]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_437/DUKE_437_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878079]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_438/DUKE_438_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879467]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_441/DUKE_441_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882961]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_444/DUKE_444_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874634]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_454/DUKE_454_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881118]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_457/DUKE_457_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876670]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_464/DUKE_464_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879376]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_465/DUKE_465_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880906]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_468/DUKE_468_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878394]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_470/DUKE_470_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871680]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_474/DUKE_474_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872641]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_480/DUKE_480_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879248]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_482/DUKE_482_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881651]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_486/DUKE_486_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882508]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_489/DUKE_489_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875212]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_491/DUKE_491_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874327]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_501/DUKE_501_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877213]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_506/DUKE_506_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880043]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_507/DUKE_507_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871118]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_508/DUKE_508_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877846]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_512/DUKE_512_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878624]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_514/DUKE_514_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879683]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_517/DUKE_517_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881169]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_521/DUKE_521_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882583]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_525/DUKE_525_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879981]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_527/DUKE_527_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872295]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_530/DUKE_530_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871136]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_534/DUKE_534_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881141]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_535/DUKE_535_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883249]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_539/DUKE_539_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883051]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_541/DUKE_541_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877373]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_543/DUKE_543_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878861]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_545/DUKE_545_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881167]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_546/DUKE_546_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874770]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_552/DUKE_552_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882226]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_558/DUKE_558_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875033]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_559/DUKE_559_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877766]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_560/DUKE_560_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882200]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_562/DUKE_562_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879506]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_567/DUKE_567_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876634]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_568/DUKE_568_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875756]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_573/DUKE_573_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880063]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_577/DUKE_577_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872006]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_585/DUKE_585_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882356]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_590/DUKE_590_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881063]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_592/DUKE_592_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879517]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_595/DUKE_595_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873022]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_597/DUKE_597_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878680]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_605/DUKE_605_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878595]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_607/DUKE_607_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878961]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_609/DUKE_609_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879430]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_610/DUKE_610_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878724]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_612/DUKE_612_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877152]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_614/DUKE_614_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877105]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_615/DUKE_615_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872319]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_616/DUKE_616_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877710]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_618/DUKE_618_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877423]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_623/DUKE_623_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880573]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_633/DUKE_633_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872734]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_636/DUKE_636_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879041]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_640/DUKE_640_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882126]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_641/DUKE_641_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873112]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_642/DUKE_642_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873937]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_645/DUKE_645_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873701]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_650/DUKE_650_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874398]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_651/DUKE_651_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876666]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_652/DUKE_652_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882913]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_656/DUKE_656_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872424]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_660/DUKE_660_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875339]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_662/DUKE_662_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874504]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_663/DUKE_663_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878089]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_666/DUKE_666_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880368]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_670/DUKE_670_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883600]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_672/DUKE_672_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880865]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_677/DUKE_677_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878931]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_679/DUKE_679_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874647]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_681/DUKE_681_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873393]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_684/DUKE_684_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875250]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_685/DUKE_685_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877720]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_686/DUKE_686_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881250]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_687/DUKE_687_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877689]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_688/DUKE_688_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880872]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_691/DUKE_691_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873850]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_693/DUKE_693_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879057]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_694/DUKE_694_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879926]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_697/DUKE_697_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883839]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_710/DUKE_710_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878673]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_717/DUKE_717_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876762]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_718/DUKE_718_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879669]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_723/DUKE_723_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876581]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_724/DUKE_724_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880268]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_725/DUKE_725_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880020]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_735/DUKE_735_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883586]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_746/DUKE_746_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882011]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_751/DUKE_751_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873913]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_754/DUKE_754_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883234]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_757/DUKE_757_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874487]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_758/DUKE_758_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878732]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_762/DUKE_762_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871380]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_765/DUKE_765_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875107]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_774/DUKE_774_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883212]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_775/DUKE_775_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878742]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_776/DUKE_776_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875444]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_778/DUKE_778_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876646]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_780/DUKE_780_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874217]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_789/DUKE_789_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883363]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_790/DUKE_790_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880714]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_792/DUKE_792_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874351]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_797/DUKE_797_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879800]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_799/DUKE_799_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882295]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_804/DUKE_804_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876060]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_805/DUKE_805_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872460]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_809/DUKE_809_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879689]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_812/DUKE_812_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880239]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_816/DUKE_816_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876285]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_817/DUKE_817_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883436]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_822/DUKE_822_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878374]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_830/DUKE_830_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875917]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_831/DUKE_831_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880901]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_832/DUKE_832_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879284]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_833/DUKE_833_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872713]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_834/DUKE_834_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871651]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_836/DUKE_836_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874670]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_839/DUKE_839_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878667]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_847/DUKE_847_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877128]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_850/DUKE_850_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871269]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_860/DUKE_860_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872900]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_865/DUKE_865_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883342]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_869/DUKE_869_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874260]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_873/DUKE_873_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873653]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_874/DUKE_874_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874827]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_879/DUKE_879_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882436]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_882/DUKE_882_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872178]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_883/DUKE_883_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876241]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_884/DUKE_884_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877511]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_885/DUKE_885_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872724]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_886/DUKE_886_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879795]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_891/DUKE_891_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879972]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_899/DUKE_899_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881706]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_907/DUKE_907_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876936]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_914/DUKE_914_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872391]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_915/DUKE_915_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876317]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_916/DUKE_916_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872543]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/DUKE_917/DUKE_917_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883532]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1001/ISPY1_1001_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878172]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1002/ISPY1_1002_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879005]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1003/ISPY1_1003_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880468]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1004/ISPY1_1004_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878574]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1005/ISPY1_1005_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877056]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1007/ISPY1_1007_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878718]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1008/ISPY1_1008_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875548]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1009/ISPY1_1009_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878892]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1010/ISPY1_1010_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871461]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1011/ISPY1_1011_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877959]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1012/ISPY1_1012_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880636]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1013/ISPY1_1013_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878291]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1015/ISPY1_1015_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875155]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1016/ISPY1_1016_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880811]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1017/ISPY1_1017_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872818]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1021/ISPY1_1021_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882537]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1025/ISPY1_1025_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879574]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1027/ISPY1_1027_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878037]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1029/ISPY1_1029_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877506]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1030/ISPY1_1030_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873821]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1031/ISPY1_1031_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874376]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1032/ISPY1_1032_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879914]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1034/ISPY1_1034_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875316]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1035/ISPY1_1035_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874163]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1036/ISPY1_1036_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874592]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1037/ISPY1_1037_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881903]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1038/ISPY1_1038_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883427]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1040/ISPY1_1040_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875008]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1041/ISPY1_1041_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875234]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1042/ISPY1_1042_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883788]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1049/ISPY1_1049_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875737]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1051/ISPY1_1051_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879781]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1053/ISPY1_1053_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873997]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1054/ISPY1_1054_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877311]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1056/ISPY1_1056_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876174]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1058/ISPY1_1058_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883896]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1060/ISPY1_1060_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878429]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1061/ISPY1_1061_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880856]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1062/ISPY1_1062_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881506]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1064/ISPY1_1064_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878245]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1065/ISPY1_1065_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875952]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1066/ISPY1_1066_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883007]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1067/ISPY1_1067_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883268]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1069/ISPY1_1069_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875865]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1070/ISPY1_1070_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875291]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1072/ISPY1_1072_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878453]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1073/ISPY1_1073_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883299]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1074/ISPY1_1074_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879125]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1075/ISPY1_1075_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882627]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1077/ISPY1_1077_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883072]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1078/ISPY1_1078_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880336]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1082/ISPY1_1082_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879344]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1083/ISPY1_1083_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879838]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1084/ISPY1_1084_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871525]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1087/ISPY1_1087_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876710]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1088/ISPY1_1088_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871518]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1089/ISPY1_1089_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883124]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1090/ISPY1_1090_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879052]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1094/ISPY1_1094_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880840]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1096/ISPY1_1096_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873942]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1097/ISPY1_1097_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881827]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1098/ISPY1_1098_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880039]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1099/ISPY1_1099_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879598]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1100/ISPY1_1100_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873320]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1101/ISPY1_1101_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876765]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1102/ISPY1_1102_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881684]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1103/ISPY1_1103_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879186]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1104/ISPY1_1104_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873800]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1106/ISPY1_1106_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876952]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1107/ISPY1_1107_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878224]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1112/ISPY1_1112_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872239]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1114/ISPY1_1114_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881834]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1117/ISPY1_1117_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872212]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1122/ISPY1_1122_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882527]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1123/ISPY1_1123_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883508]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1124/ISPY1_1124_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879348]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1125/ISPY1_1125_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881437]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1127/ISPY1_1127_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881947]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1128/ISPY1_1128_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873155]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1129/ISPY1_1129_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878287]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1130/ISPY1_1130_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881211]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1132/ISPY1_1132_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873193]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1134/ISPY1_1134_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882532]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1135/ISPY1_1135_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879067]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1136/ISPY1_1136_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881228]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1137/ISPY1_1137_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878810]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1139/ISPY1_1139_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873621]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1140/ISPY1_1140_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883246]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1141/ISPY1_1141_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882175]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1142/ISPY1_1142_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878879]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1144/ISPY1_1144_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881146]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1145/ISPY1_1145_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872192]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1146/ISPY1_1146_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874241]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1147/ISPY1_1147_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874337]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1148/ISPY1_1148_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882278]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1149/ISPY1_1149_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871350]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1150/ISPY1_1150_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873307]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1151/ISPY1_1151_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882812]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1152/ISPY1_1152_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874079]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1155/ISPY1_1155_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876309]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1156/ISPY1_1156_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875087]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1157/ISPY1_1157_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876503]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1158/ISPY1_1158_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872905]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1159/ISPY1_1159_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873060]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1160/ISPY1_1160_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875961]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1161/ISPY1_1161_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879317]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1163/ISPY1_1163_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883602]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1164/ISPY1_1164_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882717]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1165/ISPY1_1165_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879380]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1166/ISPY1_1166_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883869]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1167/ISPY1_1167_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881633]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1168/ISPY1_1168_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872523]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1169/ISPY1_1169_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871170]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1171/ISPY1_1171_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873521]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1172/ISPY1_1172_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878073]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1173/ISPY1_1173_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875625]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1174/ISPY1_1174_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879924]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1175/ISPY1_1175_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883564]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1176/ISPY1_1176_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876599]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1177/ISPY1_1177_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880219]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1179/ISPY1_1179_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883433]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1180/ISPY1_1180_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871627]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1181/ISPY1_1181_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883292]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1182/ISPY1_1182_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882469]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1183/ISPY1_1183_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882856]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1184/ISPY1_1184_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877666]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1185/ISPY1_1185_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873201]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1187/ISPY1_1187_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880169]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1188/ISPY1_1188_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872825]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1189/ISPY1_1189_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873127]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1191/ISPY1_1191_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878748]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1192/ISPY1_1192_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877200]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1193/ISPY1_1193_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873886]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1194/ISPY1_1194_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871781]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1196/ISPY1_1196_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878799]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1197/ISPY1_1197_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871588]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1198/ISPY1_1198_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873316]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1199/ISPY1_1199_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879409]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1201/ISPY1_1201_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874571]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1202/ISPY1_1202_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879355]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1203/ISPY1_1203_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878390]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1204/ISPY1_1204_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877084]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1207/ISPY1_1207_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875990]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1208/ISPY1_1208_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881781]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1209/ISPY1_1209_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877597]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1210/ISPY1_1210_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876258]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1212/ISPY1_1212_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879896]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1215/ISPY1_1215_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873853]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1216/ISPY1_1216_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872091]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1217/ISPY1_1217_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879268]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1218/ISPY1_1218_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878114]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1219/ISPY1_1219_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880632]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1220/ISPY1_1220_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880521]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1221/ISPY1_1221_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881349]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1222/ISPY1_1222_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872691]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1223/ISPY1_1223_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880007]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1224/ISPY1_1224_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871886]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1225/ISPY1_1225_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879657]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1226/ISPY1_1226_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874841]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1227/ISPY1_1227_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880203]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1228/ISPY1_1228_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882995]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1229/ISPY1_1229_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873504]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1230/ISPY1_1230_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879550]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1231/ISPY1_1231_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882991]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1233/ISPY1_1233_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882336]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1234/ISPY1_1234_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877489]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1235/ISPY1_1235_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883209]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1236/ISPY1_1236_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873838]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1237/ISPY1_1237_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881628]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1238/ISPY1_1238_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881426]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY1_1239/ISPY1_1239_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881559]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_100899/ISPY2_100899_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877156]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_102011/ISPY2_102011_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879749]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_102212/ISPY2_102212_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881491]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_103693/ISPY2_103693_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872915]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_103939/ISPY2_103939_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877785]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_104268/ISPY2_104268_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881718]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_104384/ISPY2_104384_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881469]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_105286/ISPY2_105286_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883696]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_105513/ISPY2_105513_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878416]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_107700/ISPY2_107700_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878639]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_108939/ISPY2_108939_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873957]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_108969/ISPY2_108969_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880566]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_109623/ISPY2_109623_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880381]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_109874/ISPY2_109874_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872883]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_109980/ISPY2_109980_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873096]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_111004/ISPY2_111004_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878476]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_111038/ISPY2_111038_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64879135]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_111344/ISPY2_111344_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872046]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_111646/ISPY2_111646_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876592]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_111674/ISPY2_111674_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877678]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_111881/ISPY2_111881_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872948]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_112606/ISPY2_112606_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872259]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_114087/ISPY2_114087_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872583]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_115638/ISPY2_115638_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878068]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_115987/ISPY2_115987_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883242]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_116165/ISPY2_116165_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873725]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_116603/ISPY2_116603_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874129]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_117424/ISPY2_117424_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875742]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_117707/ISPY2_117707_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880616]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_118307/ISPY2_118307_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871636]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_119928/ISPY2_119928_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883617]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_120422/ISPY2_120422_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876681]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_122287/ISPY2_122287_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882383]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_122579/ISPY2_122579_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882814]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_122795/ISPY2_122795_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64873568]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_123660/ISPY2_123660_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882291]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_125130/ISPY2_125130_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881016]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_125418/ISPY2_125418_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878515]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_127675/ISPY2_127675_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882072]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_127791/ISPY2_127791_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883479]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_128051/ISPY2_128051_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882876]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_128675/ISPY2_128675_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877177]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_129837/ISPY2_129837_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64876225]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_129973/ISPY2_129973_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875192]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_130580/ISPY2_130580_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880072]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_130892/ISPY2_130892_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881916]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_131595/ISPY2_131595_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878157]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_131961/ISPY2_131961_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872566]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_132463/ISPY2_132463_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882312]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_133650/ISPY2_133650_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64883200]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_134526/ISPY2_134526_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878163]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_136536/ISPY2_136536_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871536]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_138027/ISPY2_138027_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880225]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_138425/ISPY2_138425_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64877615]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_139137/ISPY2_139137_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64871877]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_139771/ISPY2_139771_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64872764]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_139973/ISPY2_139973_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64874056]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_141782/ISPY2_141782_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875824]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_142688/ISPY2_142688_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882890]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_144302/ISPY2_144302_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875888]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_145513/ISPY2_145513_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64882898]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_145777/ISPY2_145777_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64880053]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_146033/ISPY2_146033_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878361]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_146987/ISPY2_146987_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64878869]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_147139/ISPY2_147139_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64875117]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_148357/ISPY2_148357_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]

[syn64881132]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_149654/ISPY2_149654_0000.nii.gz, skipping download.

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s]
Downloading files: 100%|██████████| 3.72M/3.72M [00:00<00:00, 3.85MB/s]

[syn64881975]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_150547/ISPY2_150547_0000.nii.gz

Downloading files: 100%|█████████▉| 8.36M/8.36M [00:01<00:00, 4.73MB/s]

[syn64874701]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_151230/ISPY2_151230_0000.nii.gz

Downloading files: 100%|█████████▉| 8.36M/8.36M [00:02<00:00, 4.02MB/s]

[syn64872114]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_151481/ISPY2_151481_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 27.5M/27.5M [00:03<00:00, 7.59MB/s]

[syn64879281]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_151980/ISPY2_151980_0000.nii.gz

Downloading files: 100%|█████████▉| 27.5M/27.5M [00:03<00:00, 7.03MB/s]

[syn64882427]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_152090/ISPY2_152090_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 32.6M/32.6M [00:04<00:00, 6.89MB/s]

[syn64883652]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_152197/ISPY2_152197_0000.nii.gz

Downloading files: 100%|█████████▉| 35.4M/35.4M [00:05<00:00, 6.31MB/s]

[syn64878657]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_153327/ISPY2_153327_0000.nii.gz

Downloading files: 100%|█████████▉| 35.4M/35.4M [00:05<00:00, 5.99MB/s]

[syn64875539]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_153880/ISPY2_153880_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 35.4M/35.4M [00:06<00:00, 5.66MB/s]

[syn64880816]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_154293/ISPY2_154293_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 35.4M/35.4M [00:06<00:00, 5.39MB/s]

[syn64878783]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_155171/ISPY2_155171_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 35.4M/35.4M [00:06<00:00, 5.13MB/s]

[syn64874479]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_156163/ISPY2_156163_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 35.4M/35.4M [00:07<00:00, 4.92MB/s]

[syn64873612]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_157270/ISPY2_157270_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 39.6M/39.6M [00:08<00:00, 4.89MB/s]

[syn64880542]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_157463/ISPY2_157463_0000.nii.gz

Downloading files: 100%|█████████▉| 39.6M/39.6M [00:08<00:00, 4.70MB/s]

[syn64872070]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_159284/ISPY2_159284_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 39.6M/39.6M [00:08<00:00, 4.55MB/s]

[syn64876738]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_159352/ISPY2_159352_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 44.3M/44.3M [00:09<00:00, 4.62MB/s]

[syn64875422]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_160120/ISPY2_160120_0000.nii.gz

Downloading files: 100%|█████████▉| 48.6M/48.6M [00:10<00:00, 4.67MB/s]

[syn64880141]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_162562/ISPY2_162562_0000.nii.gz

Downloading files: 100%|█████████▉| 48.6M/48.6M [00:10<00:00, 4.53MB/s]

[syn64881295]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_164468/ISPY2_164468_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 48.6M/48.6M [00:11<00:00, 4.39MB/s]

[syn64878404]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_165925/ISPY2_165925_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 59.0M/59.0M [00:12<00:00, 4.78MB/s]

[syn64882102]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_166412/ISPY2_166412_0000.nii.gz

Downloading files: 100%|█████████▉| 59.0M/59.0M [00:12<00:00, 4.65MB/s]

[syn64880576]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_166782/ISPY2_166782_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 63.6M/63.6M [00:13<00:00, 4.71MB/s]

[syn64882770]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_167271/ISPY2_167271_0000.nii.gz

Downloading files: 100%|█████████▉| 67.4M/67.4M [00:14<00:00, 4.71MB/s]

[syn64881739]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_168044/ISPY2_168044_0000.nii.gz

Downloading files: 100%|█████████▉| 67.4M/67.4M [00:14<00:00, 4.63MB/s]

[syn64881501]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_169536/ISPY2_169536_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 67.4M/67.4M [00:14<00:00, 4.52MB/s]

[syn64882285]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_169918/ISPY2_169918_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 87.4M/87.4M [00:16<00:00, 5.38MB/s]

[syn64883636]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_172168/ISPY2_172168_0000.nii.gz

Downloading files: 100%|█████████▉| 90.3M/90.3M [00:17<00:00, 5.29MB/s]

[syn64881005]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_172283/ISPY2_172283_0000.nii.gz

Downloading files: 100%|█████████▉| 90.3M/90.3M [00:17<00:00, 5.19MB/s]

[syn64878711]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_172366/ISPY2_172366_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 90.3M/90.3M [00:17<00:00, 5.11MB/s]

[syn64883778]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_174903/ISPY2_174903_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 101M/101M [00:18<00:00, 5.35MB/s]

[syn64882764]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_174904/ISPY2_174904_0000.nii.gz

Downloading files: 100%|█████████▉| 101M/101M [00:19<00:00, 5.26MB/s]

[syn64875597]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_177795/ISPY2_177795_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 101M/101M [00:19<00:00, 5.19MB/s]

[syn64873397]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_178649/ISPY2_178649_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 106M/106M [00:20<00:00, 5.23MB/s]

[syn64878690]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_178815/ISPY2_178815_0000.nii.gz

Downloading files: 100%|█████████▉| 106M/106M [00:20<00:00, 5.16MB/s]

[syn64875216]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_179369/ISPY2_179369_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 106M/106M [00:20<00:00, 5.09MB/s]

[syn64875287]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_179568/ISPY2_179568_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 106M/106M [00:21<00:00, 5.03MB/s]

[syn64880130]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_180027/ISPY2_180027_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 106M/106M [00:21<00:00, 4.95MB/s]

[syn64879028]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_180663/ISPY2_180663_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 116M/116M [00:22<00:00, 5.10MB/s]

[syn64882521]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_181442/ISPY2_181442_0000.nii.gz

Downloading files: 100%|█████████▉| 120M/120M [00:23<00:00, 5.11MB/s]

[syn64879175]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_181819/ISPY2_181819_0000.nii.gz

Downloading files: 100%|█████████▉| 120M/120M [00:23<00:00, 5.04MB/s]

[syn64882218]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_182346/ISPY2_182346_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 130M/130M [00:25<00:00, 5.17MB/s]

[syn64881590]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_183831/ISPY2_183831_0000.nii.gz

Downloading files: 100%|█████████▉| 135M/135M [00:25<00:00, 5.19MB/s]

[syn64883091]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_188091/ISPY2_188091_0000.nii.gz

Downloading files: 100%|█████████▉| 143M/143M [00:26<00:00, 5.30MB/s]

[syn64878253]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_188511/ISPY2_188511_0000.nii.gz

Downloading files: 100%|█████████▉| 143M/143M [00:27<00:00, 5.24MB/s]

[syn64880935]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_188700/ISPY2_188700_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 143M/143M [00:27<00:00, 5.18MB/s]

[syn64873274]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_190224/ISPY2_190224_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 143M/143M [00:27<00:00, 5.13MB/s]

[syn64883379]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_192548/ISPY2_192548_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 143M/143M [00:28<00:00, 5.08MB/s]

[syn64880247]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_194024/ISPY2_194024_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 143M/143M [00:28<00:00, 5.02MB/s]

[syn64872632]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_196024/ISPY2_196024_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 148M/148M [00:29<00:00, 5.04MB/s]

[syn64877233]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_196064/ISPY2_196064_0000.nii.gz

Downloading files: 100%|█████████▉| 148M/148M [00:29<00:00, 4.98MB/s]

[syn64880773]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_197942/ISPY2_197942_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 148M/148M [00:29<00:00, 4.93MB/s]

[syn64879033]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_198891/ISPY2_198891_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 148M/148M [00:30<00:00, 4.88MB/s]

[syn64876199]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_199115/ISPY2_199115_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 163M/163M [00:31<00:00, 5.13MB/s]

[syn64881020]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_199960/ISPY2_199960_0000.nii.gz

Downloading files: 100%|█████████▉| 173M/173M [00:32<00:00, 5.25MB/s]

[syn64879045]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_200222/ISPY2_200222_0000.nii.gz

Downloading files: 100%|█████████▉| 173M/173M [00:33<00:00, 5.20MB/s]

[syn64880736]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_201831/ISPY2_201831_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 173M/173M [00:33<00:00, 5.16MB/s]

[syn64879129]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_201873/ISPY2_201873_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 180M/180M [00:34<00:00, 5.23MB/s]

[syn64882049]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_202535/ISPY2_202535_0000.nii.gz

Downloading files: 100%|█████████▉| 180M/180M [00:34<00:00, 5.18MB/s]

[syn64873368]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_202539/ISPY2_202539_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 180M/180M [00:35<00:00, 5.14MB/s]

[syn64882405]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_202956/ISPY2_202956_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 180M/180M [00:35<00:00, 5.09MB/s]

[syn64883575]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_203060/ISPY2_203060_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 191M/191M [00:36<00:00, 5.21MB/s]

[syn64877662]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_203254/ISPY2_203254_0000.nii.gz

Downloading files: 100%|█████████▉| 191M/191M [00:36<00:00, 5.17MB/s]

[syn64881309]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_204939/ISPY2_204939_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 191M/191M [00:37<00:00, 5.13MB/s]

[syn64883512]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_208265/ISPY2_208265_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 191M/191M [00:37<00:00, 5.08MB/s]

[syn64881393]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_208303/ISPY2_208303_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 191M/191M [00:37<00:00, 5.05MB/s]

[syn64878285]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_208650/ISPY2_208650_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 191M/191M [00:38<00:00, 5.01MB/s]

[syn64883464]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_209397/ISPY2_209397_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 191M/191M [00:38<00:00, 4.97MB/s]

[syn64877315]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_209967/ISPY2_209967_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 191M/191M [00:38<00:00, 4.93MB/s]

[syn64878977]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_211408/ISPY2_211408_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 210M/210M [00:40<00:00, 5.23MB/s]

[syn64882797]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_212307/ISPY2_212307_0000.nii.gz

Downloading files: 100%|█████████▉| 215M/215M [00:40<00:00, 5.24MB/s]

[syn64878707]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_213328/ISPY2_213328_0000.nii.gz

Downloading files: 100%|█████████▉| 215M/215M [00:41<00:00, 5.20MB/s]

[syn64871717]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_213672/ISPY2_213672_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 215M/215M [00:41<00:00, 5.16MB/s]

[syn64883273]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_213913/ISPY2_213913_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 215M/215M [00:41<00:00, 5.13MB/s]

[syn64880943]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_215932/ISPY2_215932_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 215M/215M [00:42<00:00, 5.09MB/s]

[syn64873665]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_218249/ISPY2_218249_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 219M/219M [00:43<00:00, 5.08MB/s]

[syn64883109]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_218503/ISPY2_218503_0000.nii.gz

Downloading files: 100%|█████████▉| 224M/224M [00:44<00:00, 5.09MB/s]

[syn64877921]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_219545/ISPY2_219545_0000.nii.gz

Downloading files: 100%|█████████▉| 224M/224M [00:44<00:00, 5.03MB/s]

[syn64879901]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_220471/ISPY2_220471_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 224M/224M [00:44<00:00, 4.99MB/s]

[syn64872223]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_220664/ISPY2_220664_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 228M/228M [00:45<00:00, 4.99MB/s]

[syn64879450]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_220925/ISPY2_220925_0000.nii.gz

Downloading files: 100%|█████████▉| 228M/228M [00:46<00:00, 4.93MB/s]

[syn64877972]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_221375/ISPY2_221375_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 233M/233M [00:47<00:00, 4.92MB/s]

[syn64883373]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_221686/ISPY2_221686_0000.nii.gz

Downloading files: 100%|█████████▉| 239M/239M [00:48<00:00, 4.96MB/s]

[syn64879237]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_222135/ISPY2_222135_0000.nii.gz

Downloading files: 100%|█████████▉| 242M/242M [00:49<00:00, 4.93MB/s]

[syn64878261]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_223030/ISPY2_223030_0000.nii.gz

Downloading files: 100%|█████████▉| 242M/242M [00:49<00:00, 4.91MB/s]

[syn64873343]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_223526/ISPY2_223526_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 242M/242M [00:49<00:00, 4.88MB/s]

[syn64881548]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_225836/ISPY2_225836_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 248M/248M [00:50<00:00, 4.92MB/s]

[syn64876493]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_227055/ISPY2_227055_0000.nii.gz

Downloading files: 100%|█████████▉| 248M/248M [00:50<00:00, 4.88MB/s]

[syn64873549]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_227832/ISPY2_227832_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 248M/248M [00:51<00:00, 4.85MB/s]

[syn64876141]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_227881/ISPY2_227881_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 248M/248M [00:51<00:00, 4.82MB/s]

[syn64874172]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_228192/ISPY2_228192_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 253M/253M [00:52<00:00, 4.83MB/s]

[syn64880286]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_228340/ISPY2_228340_0000.nii.gz

Downloading files: 100%|█████████▉| 253M/253M [00:52<00:00, 4.81MB/s]

[syn64880455]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_229144/ISPY2_229144_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 253M/253M [00:52<00:00, 4.78MB/s]

[syn64876390]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_229328/ISPY2_229328_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 253M/253M [00:53<00:00, 4.75MB/s]

[syn64881450]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_229824/ISPY2_229824_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 253M/253M [00:53<00:00, 4.73MB/s]

[syn64878219]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_231633/ISPY2_231633_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 253M/253M [00:53<00:00, 4.70MB/s]

[syn64883535]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_233191/ISPY2_233191_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 253M/253M [00:54<00:00, 4.68MB/s]

[syn64878873]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_233832/ISPY2_233832_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 253M/253M [00:54<00:00, 4.65MB/s]

[syn64878935]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_233962/ISPY2_233962_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 253M/253M [00:54<00:00, 4.62MB/s]

[syn64883757]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_234272/ISPY2_234272_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 253M/253M [00:55<00:00, 4.60MB/s]

[syn64873683]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_234723/ISPY2_234723_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 259M/259M [00:55<00:00, 4.63MB/s]

[syn64878559]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_235995/ISPY2_235995_0000.nii.gz

Downloading files: 100%|█████████▉| 259M/259M [00:56<00:00, 4.60MB/s]

[syn64879305]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_236470/ISPY2_236470_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 259M/259M [00:56<00:00, 4.58MB/s]

[syn64872861]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_237158/ISPY2_237158_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 264M/264M [00:57<00:00, 4.59MB/s]

[syn64879160]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_238790/ISPY2_238790_0000.nii.gz

Downloading files: 100%|█████████▉| 264M/264M [00:57<00:00, 4.57MB/s]

[syn64873583]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_239061/ISPY2_239061_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 273M/273M [00:59<00:00, 4.62MB/s]

[syn64880134]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_239910/ISPY2_239910_0000.nii.gz

Downloading files: 100%|█████████▉| 273M/273M [00:59<00:00, 4.59MB/s]

[syn64878769]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_240035/ISPY2_240035_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 277M/277M [01:00<00:00, 4.59MB/s]

[syn64879699]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_240432/ISPY2_240432_0000.nii.gz

Downloading files: 100%|█████████▉| 282M/282M [01:01<00:00, 4.61MB/s]

[syn64878921]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_240957/ISPY2_240957_0000.nii.gz

Downloading files: 100%|█████████▉| 282M/282M [01:01<00:00, 4.59MB/s]

[syn64875000]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_241705/ISPY2_241705_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 287M/287M [01:02<00:00, 4.61MB/s]

[syn64881969]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_241998/ISPY2_241998_0000.nii.gz

Downloading files: 100%|█████████▉| 287M/287M [01:02<00:00, 4.58MB/s]

[syn64875375]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_242370/ISPY2_242370_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 291M/291M [01:03<00:00, 4.57MB/s]

[syn64877904]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_243836/ISPY2_243836_0000.nii.gz

Downloading files: 100%|█████████▉| 298M/298M [01:04<00:00, 4.62MB/s]

[syn64872151]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_245655/ISPY2_245655_0000.nii.gz

Downloading files: 100%|█████████▉| 298M/298M [01:04<00:00, 4.60MB/s]

[syn64872832]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_246134/ISPY2_246134_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 298M/298M [01:05<00:00, 4.58MB/s]

[syn64881509]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_247641/ISPY2_247641_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 298M/298M [01:05<00:00, 4.56MB/s]

[syn64881645]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_248255/ISPY2_248255_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 298M/298M [01:05<00:00, 4.54MB/s]

[syn64883327]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_250274/ISPY2_250274_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 318M/318M [01:07<00:00, 4.73MB/s]

[syn64883609]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_252748/ISPY2_252748_0000.nii.gz

Downloading files: 100%|█████████▉| 318M/318M [01:07<00:00, 4.71MB/s]

[syn64881820]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_253531/ISPY2_253531_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 318M/318M [01:07<00:00, 4.69MB/s]

[syn64871707]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_254060/ISPY2_254060_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 335M/335M [01:08<00:00, 4.87MB/s]

[syn64881342]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_254273/ISPY2_254273_0000.nii.gz

Downloading files: 100%|█████████▉| 352M/352M [01:10<00:00, 5.02MB/s]

[syn64874542]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_255078/ISPY2_255078_0000.nii.gz

Downloading files: 100%|█████████▉| 370M/370M [01:11<00:00, 5.18MB/s]

[syn64881861]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_255388/ISPY2_255388_0000.nii.gz

Downloading files: 100%|█████████▉| 374M/374M [01:12<00:00, 5.18MB/s]

[syn64881125]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_255535/ISPY2_255535_0000.nii.gz

Downloading files: 100%|█████████▉| 374M/374M [01:12<00:00, 5.16MB/s]

[syn64878791]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_255577/ISPY2_255577_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 374M/374M [01:12<00:00, 5.14MB/s]

[syn64875385]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_257735/ISPY2_257735_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 374M/374M [01:13<00:00, 5.12MB/s]

[syn64879201]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_259206/ISPY2_259206_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 374M/374M [01:13<00:00, 5.10MB/s]

[syn64873213]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_259899/ISPY2_259899_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 374M/374M [01:13<00:00, 5.07MB/s]

[syn64877603]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_261304/ISPY2_261304_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 374M/374M [01:14<00:00, 5.05MB/s]

[syn64883454]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_262131/ISPY2_262131_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 374M/374M [01:14<00:00, 5.03MB/s]

[syn64874866]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_263143/ISPY2_263143_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 374M/374M [01:14<00:00, 5.01MB/s]

[syn64877396]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_264305/ISPY2_264305_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 382M/382M [01:15<00:00, 5.06MB/s]

[syn64873734]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_264678/ISPY2_264678_0000.nii.gz

Downloading files: 100%|█████████▉| 386M/386M [01:16<00:00, 5.06MB/s]

[syn64880473]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_266509/ISPY2_266509_0000.nii.gz

Downloading files: 100%|█████████▉| 391M/391M [01:17<00:00, 5.06MB/s]

[syn64873473]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_266840/ISPY2_266840_0000.nii.gz

Downloading files: 100%|█████████▉| 401M/401M [01:18<00:00, 5.11MB/s]

[syn64882346]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_267306/ISPY2_267306_0000.nii.gz

Downloading files: 100%|█████████▉| 401M/401M [01:18<00:00, 5.09MB/s]

[syn64882740]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_268937/ISPY2_268937_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 401M/401M [01:19<00:00, 5.07MB/s]

[syn64873360]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_269899/ISPY2_269899_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 406M/406M [01:19<00:00, 5.08MB/s]

[syn64881236]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_273691/ISPY2_273691_0000.nii.gz

Downloading files: 100%|█████████▉| 417M/417M [01:21<00:00, 5.13MB/s]

[syn64877737]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_273745/ISPY2_273745_0000.nii.gz

Downloading files: 100%|█████████▉| 417M/417M [01:21<00:00, 5.11MB/s]

[syn64882572]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_275034/ISPY2_275034_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 417M/417M [01:21<00:00, 5.09MB/s]

[syn64874626]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_275626/ISPY2_275626_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 421M/421M [01:22<00:00, 5.09MB/s]

[syn64881424]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_277848/ISPY2_277848_0000.nii.gz

Downloading files: 100%|█████████▉| 429M/429M [01:23<00:00, 5.14MB/s]

[syn64879588]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_277888/ISPY2_277888_0000.nii.gz

Downloading files: 100%|█████████▉| 429M/429M [01:23<00:00, 5.12MB/s]

[syn64882516]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_279902/ISPY2_279902_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 434M/434M [01:24<00:00, 5.12MB/s]

[syn64875684]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_280375/ISPY2_280375_0000.nii.gz

Downloading files: 100%|█████████▉| 434M/434M [01:25<00:00, 5.10MB/s]

[syn64878102]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_282082/ISPY2_282082_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 434M/434M [01:25<00:00, 5.08MB/s]

[syn64881793]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_282644/ISPY2_282644_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 437M/437M [01:26<00:00, 5.07MB/s]

[syn64876095]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_282777/ISPY2_282777_0000.nii.gz

Downloading files: 100%|█████████▉| 437M/437M [01:26<00:00, 5.05MB/s]

[syn64882863]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_283070/ISPY2_283070_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 441M/441M [01:27<00:00, 5.05MB/s]

[syn64883767]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_284355/ISPY2_284355_0000.nii.gz

Downloading files: 100%|█████████▉| 441M/441M [01:28<00:00, 5.01MB/s]

[syn64881924]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_284443/ISPY2_284443_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 441M/441M [01:28<00:00, 5.00MB/s]

[syn64878911]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_284593/ISPY2_284593_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 446M/446M [01:29<00:00, 5.00MB/s]

[syn64873965]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_285339/ISPY2_285339_0000.nii.gz

Downloading files: 100%|█████████▉| 451M/451M [01:29<00:00, 5.02MB/s]

[syn64883855]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_286984/ISPY2_286984_0000.nii.gz

Downloading files: 100%|█████████▉| 456M/456M [01:30<00:00, 5.02MB/s]

[syn64879988]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_287300/ISPY2_287300_0000.nii.gz

Downloading files: 100%|█████████▉| 456M/456M [01:31<00:00, 5.00MB/s]

[syn64881774]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_287961/ISPY2_287961_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 456M/456M [01:31<00:00, 4.99MB/s]

[syn64873083]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_289107/ISPY2_289107_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 461M/461M [01:32<00:00, 5.00MB/s]

[syn64882391]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_289420/ISPY2_289420_0000.nii.gz

Downloading files: 100%|█████████▉| 468M/468M [01:33<00:00, 5.02MB/s]

[syn64875399]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_290413/ISPY2_290413_0000.nii.gz

Downloading files: 100%|█████████▉| 472M/472M [01:34<00:00, 5.01MB/s]

[syn64881725]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_291515/ISPY2_291515_0000.nii.gz

Downloading files: 100%|█████████▉| 477M/477M [01:35<00:00, 5.01MB/s]

[syn64881442]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_293142/ISPY2_293142_0000.nii.gz

Downloading files: 100%|█████████▉| 481M/481M [01:35<00:00, 5.02MB/s]

[syn64882339]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_294176/ISPY2_294176_0000.nii.gz

Downloading files: 100%|█████████▉| 489M/489M [01:36<00:00, 5.05MB/s]

[syn64876513]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_294265/ISPY2_294265_0000.nii.gz

Downloading files: 100%|█████████▉| 489M/489M [01:37<00:00, 5.04MB/s]

[syn64879624]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_294739/ISPY2_294739_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 489M/489M [01:37<00:00, 5.02MB/s]

[syn64879194]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_296123/ISPY2_296123_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 489M/489M [01:37<00:00, 5.01MB/s]

[syn64879968]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_296841/ISPY2_296841_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 489M/489M [01:38<00:00, 4.99MB/s]

[syn64871561]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_298101/ISPY2_298101_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 511M/511M [01:39<00:00, 5.15MB/s]

[syn64872442]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_299364/ISPY2_299364_0000.nii.gz

Downloading files: 100%|█████████▉| 514M/514M [01:40<00:00, 5.14MB/s]

[syn64881800]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_299840/ISPY2_299840_0000.nii.gz

Downloading files: 100%|█████████▉| 514M/514M [01:40<00:00, 5.12MB/s]

[syn64876961]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_299962/ISPY2_299962_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 514M/514M [01:40<00:00, 5.11MB/s]

[syn64883793]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_300724/ISPY2_300724_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 514M/514M [01:41<00:00, 5.09MB/s]

[syn64878469]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_301289/ISPY2_301289_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 514M/514M [01:41<00:00, 5.07MB/s]

[syn64879299]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_301665/ISPY2_301665_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 514M/514M [01:41<00:00, 5.06MB/s]

[syn64873424]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_301968/ISPY2_301968_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 519M/519M [01:42<00:00, 5.07MB/s]

[syn64877476]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_303685/ISPY2_303685_0000.nii.gz

Downloading files: 100%|█████████▉| 529M/529M [01:43<00:00, 5.10MB/s]

[syn64881303]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_303947/ISPY2_303947_0000.nii.gz

Downloading files: 100%|█████████▉| 539M/539M [01:44<00:00, 5.14MB/s]

[syn64871869]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_306127/ISPY2_306127_0000.nii.gz

Downloading files: 100%|█████████▉| 542M/542M [01:45<00:00, 5.13MB/s]

[syn64880597]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_306401/ISPY2_306401_0000.nii.gz

Downloading files: 100%|█████████▉| 542M/542M [01:45<00:00, 5.12MB/s]

[syn64879072]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_307659/ISPY2_307659_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 553M/553M [01:47<00:00, 5.16MB/s]

[syn64877405]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_309830/ISPY2_309830_0000.nii.gz

Downloading files: 100%|█████████▉| 553M/553M [01:47<00:00, 5.15MB/s]

[syn64878132]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_311316/ISPY2_311316_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 553M/553M [01:47<00:00, 5.13MB/s]

[syn64883387]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_311455/ISPY2_311455_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 553M/553M [01:48<00:00, 5.12MB/s]

[syn64877432]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_313243/ISPY2_313243_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 556M/556M [01:49<00:00, 5.09MB/s]

[syn64875899]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_313672/ISPY2_313672_0000.nii.gz

Downloading files: 100%|█████████▉| 556M/556M [01:49<00:00, 5.08MB/s]

[syn64879651]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_316996/ISPY2_316996_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 556M/556M [01:49<00:00, 5.07MB/s]

[syn64883452]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_317131/ISPY2_317131_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 560M/560M [01:50<00:00, 5.07MB/s]

[syn64879437]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_317402/ISPY2_317402_0000.nii.gz

Downloading files: 100%|█████████▉| 565M/565M [01:51<00:00, 5.08MB/s]

[syn64875308]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_317641/ISPY2_317641_0000.nii.gz

Downloading files: 100%|█████████▉| 570M/570M [01:52<00:00, 5.08MB/s]

[syn64877864]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_318293/ISPY2_318293_0000.nii.gz

Downloading files: 100%|█████████▉| 570M/570M [01:52<00:00, 5.07MB/s]

[syn64874692]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_318407/ISPY2_318407_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 579M/579M [01:53<00:00, 5.10MB/s]

[syn64880532]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_318438/ISPY2_318438_0000.nii.gz

Downloading files: 100%|█████████▉| 579M/579M [01:53<00:00, 5.08MB/s]

[syn64881597]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_318569/ISPY2_318569_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 579M/579M [01:54<00:00, 5.07MB/s]

[syn64883312]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_319324/ISPY2_319324_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 579M/579M [01:54<00:00, 5.05MB/s]

[syn64881056]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_320538/ISPY2_320538_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 579M/579M [01:54<00:00, 5.04MB/s]

[syn64872600]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_323721/ISPY2_323721_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 579M/579M [01:55<00:00, 5.03MB/s]

[syn64882301]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_324021/ISPY2_324021_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 579M/579M [01:55<00:00, 5.01MB/s]

[syn64880881]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_326202/ISPY2_326202_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 579M/579M [01:55<00:00, 5.00MB/s]

[syn64882905]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_326433/ISPY2_326433_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 579M/579M [01:56<00:00, 4.99MB/s]

[syn64874196]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_327133/ISPY2_327133_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 579M/579M [01:56<00:00, 4.97MB/s]

[syn64882262]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_327142/ISPY2_327142_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 582M/582M [01:57<00:00, 4.96MB/s]

[syn64883064]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_327917/ISPY2_327917_0000.nii.gz

Downloading files: 100%|█████████▉| 582M/582M [01:57<00:00, 4.95MB/s]

[syn64875640]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_328160/ISPY2_328160_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 582M/582M [01:58<00:00, 4.93MB/s]

[syn64882923]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_329076/ISPY2_329076_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 582M/582M [01:58<00:00, 4.91MB/s]

[syn64874889]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_329941/ISPY2_329941_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 582M/582M [01:58<00:00, 4.90MB/s]

[syn64881991]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_330134/ISPY2_330134_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 592M/592M [02:00<00:00, 4.92MB/s]

[syn64882850]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_331192/ISPY2_331192_0000.nii.gz

Downloading files: 100%|█████████▉| 592M/592M [02:00<00:00, 4.91MB/s]

[syn64880322]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_332655/ISPY2_332655_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 592M/592M [02:00<00:00, 4.90MB/s]

[syn64876471]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_333145/ISPY2_333145_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 592M/592M [02:01<00:00, 4.89MB/s]

[syn64881385]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_335091/ISPY2_335091_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 592M/592M [02:01<00:00, 4.88MB/s]

[syn64874833]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_335536/ISPY2_335536_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 602M/602M [02:02<00:00, 4.91MB/s]

[syn64873714]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_340186/ISPY2_340186_0000.nii.gz

Downloading files: 100%|█████████▉| 602M/602M [02:02<00:00, 4.90MB/s]

[syn64881331]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_341238/ISPY2_341238_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 602M/602M [02:03<00:00, 4.89MB/s]

[syn64882113]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_342142/ISPY2_342142_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 602M/602M [02:03<00:00, 4.88MB/s]

[syn64874560]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_342959/ISPY2_342959_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 607M/607M [02:04<00:00, 4.88MB/s]

[syn64880976]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_342996/ISPY2_342996_0000.nii.gz

Downloading files: 100%|█████████▉| 612M/612M [02:05<00:00, 4.89MB/s]

[syn64876189]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_343898/ISPY2_343898_0000.nii.gz

Downloading files: 100%|█████████▉| 612M/612M [02:05<00:00, 4.88MB/s]

[syn64880402]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_345460/ISPY2_345460_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 612M/612M [02:05<00:00, 4.87MB/s]

[syn64871438]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_345483/ISPY2_345483_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 612M/612M [02:06<00:00, 4.86MB/s]

[syn64883127]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_345574/ISPY2_345574_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 612M/612M [02:06<00:00, 4.85MB/s]

[syn64881847]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_345907/ISPY2_345907_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 616M/616M [02:07<00:00, 4.85MB/s]

[syn64883015]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_347516/ISPY2_347516_0000.nii.gz

Downloading files: 100%|█████████▉| 616M/616M [02:07<00:00, 4.83MB/s]

[syn64877642]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_348009/ISPY2_348009_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 616M/616M [02:07<00:00, 4.82MB/s]

[syn64880101]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_349225/ISPY2_349225_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 621M/621M [02:08<00:00, 4.82MB/s]

[syn64871835]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_349330/ISPY2_349330_0000.nii.gz

Downloading files: 100%|█████████▉| 621M/621M [02:09<00:00, 4.81MB/s]

[syn64878529]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_349639/ISPY2_349639_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 635M/635M [02:10<00:00, 4.87MB/s]

[syn64882090]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_350331/ISPY2_350331_0000.nii.gz

Downloading files: 100%|█████████▉| 638M/638M [02:11<00:00, 4.86MB/s]

[syn64883035]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_353318/ISPY2_353318_0000.nii.gz

Downloading files: 100%|█████████▉| 641M/641M [02:12<00:00, 4.86MB/s]

[syn64872812]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_355292/ISPY2_355292_0000.nii.gz

Downloading files: 100%|█████████▉| 650M/650M [02:13<00:00, 4.88MB/s]

[syn64882149]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_355942/ISPY2_355942_0000.nii.gz

Downloading files: 100%|█████████▉| 650M/650M [02:13<00:00, 4.87MB/s]

[syn64880346]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_356399/ISPY2_356399_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 657M/657M [02:14<00:00, 4.89MB/s]

[syn64878365]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_356431/ISPY2_356431_0000.nii.gz

Downloading files: 100%|█████████▉| 671M/671M [02:15<00:00, 4.94MB/s]

[syn64882726]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_356684/ISPY2_356684_0000.nii.gz

Downloading files: 100%|█████████▉| 671M/671M [02:16<00:00, 4.93MB/s]

[syn64882000]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_357017/ISPY2_357017_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 671M/671M [02:16<00:00, 4.92MB/s]

[syn64883265]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_357034/ISPY2_357034_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 671M/671M [02:16<00:00, 4.91MB/s]

[syn64873148]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_360937/ISPY2_360937_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 671M/671M [02:16<00:00, 4.90MB/s]

[syn64880429]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_361701/ISPY2_361701_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 675M/675M [02:17<00:00, 4.90MB/s]

[syn64879872]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_362150/ISPY2_362150_0000.nii.gz

Downloading files: 100%|█████████▉| 686M/686M [02:19<00:00, 4.93MB/s]

[syn64882759]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_362993/ISPY2_362993_0000.nii.gz

Downloading files: 100%|█████████▉| 693M/693M [02:19<00:00, 4.96MB/s]

[syn64872162]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_363669/ISPY2_363669_0000.nii.gz

Downloading files: 100%|█████████▉| 693M/693M [02:20<00:00, 4.94MB/s]

[syn64878355]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_366120/ISPY2_366120_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 693M/693M [02:20<00:00, 4.93MB/s]

[syn64877839]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_367682/ISPY2_367682_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 693M/693M [02:20<00:00, 4.92MB/s]

[syn64871467]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_369040/ISPY2_369040_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 693M/693M [02:21<00:00, 4.91MB/s]

[syn64876879]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_371528/ISPY2_371528_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 693M/693M [02:21<00:00, 4.90MB/s]

[syn64877954]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_373346/ISPY2_373346_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 693M/693M [02:21<00:00, 4.89MB/s]

[syn64881374]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_373672/ISPY2_373672_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 693M/693M [02:22<00:00, 4.88MB/s]

[syn64882831]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_374106/ISPY2_374106_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 701M/701M [02:22<00:00, 4.90MB/s]

[syn64882676]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_374121/ISPY2_374121_0000.nii.gz

Downloading files: 100%|█████████▉| 701M/701M [02:23<00:00, 4.89MB/s]

[syn64879908]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_375342/ISPY2_375342_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 705M/705M [02:23<00:00, 4.90MB/s]

[syn64874302]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_375455/ISPY2_375455_0000.nii.gz

Downloading files: 100%|█████████▉| 709M/709M [02:24<00:00, 4.89MB/s]

[syn64879149]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_376676/ISPY2_376676_0000.nii.gz

Downloading files: 100%|█████████▉| 709M/709M [02:25<00:00, 4.88MB/s]

[syn64871800]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_377460/ISPY2_377460_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 714M/714M [02:26<00:00, 4.88MB/s]

[syn64875923]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_378401/ISPY2_378401_0000.nii.gz

Downloading files: 100%|█████████▉| 714M/714M [02:26<00:00, 4.87MB/s]

[syn64874419]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_378885/ISPY2_378885_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 719M/719M [02:27<00:00, 4.88MB/s]

[syn64879465]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_380239/ISPY2_380239_0000.nii.gz

Downloading files: 100%|█████████▉| 724M/724M [02:27<00:00, 4.89MB/s]

[syn64883445]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_380769/ISPY2_380769_0000.nii.gz

Downloading files: 100%|█████████▉| 729M/729M [02:28<00:00, 4.90MB/s]

[syn64879322]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_380972/ISPY2_380972_0000.nii.gz

Downloading files: 100%|█████████▉| 736M/736M [02:29<00:00, 4.91MB/s]

[syn64874015]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_382853/ISPY2_382853_0000.nii.gz

Downloading files: 100%|█████████▉| 736M/736M [02:30<00:00, 4.90MB/s]

[syn64877219]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_383456/ISPY2_383456_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 740M/740M [02:30<00:00, 4.90MB/s]

[syn64879255]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_384830/ISPY2_384830_0000.nii.gz

Downloading files: 100%|█████████▉| 740M/740M [02:31<00:00, 4.89MB/s]

[syn64879821]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_386664/ISPY2_386664_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 749M/749M [02:32<00:00, 4.91MB/s]

[syn64879099]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_388581/ISPY2_388581_0000.nii.gz

Downloading files: 100%|█████████▉| 755M/755M [02:33<00:00, 4.92MB/s]

[syn64876866]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_391942/ISPY2_391942_0000.nii.gz

Downloading files: 100%|█████████▉| 755M/755M [02:33<00:00, 4.91MB/s]

[syn64883045]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_395076/ISPY2_395076_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 755M/755M [02:33<00:00, 4.90MB/s]

[syn64880749]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_395249/ISPY2_395249_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 755M/755M [02:34<00:00, 4.89MB/s]

[syn64879478]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_395379/ISPY2_395379_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 755M/755M [02:34<00:00, 4.88MB/s]

[syn64880668]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_396723/ISPY2_396723_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 765M/765M [02:35<00:00, 4.91MB/s]

[syn64879582]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_397505/ISPY2_397505_0000.nii.gz

Downloading files: 100%|█████████▉| 765M/765M [02:35<00:00, 4.90MB/s]

[syn64877938]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_399478/ISPY2_399478_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 765M/765M [02:36<00:00, 4.89MB/s]

[syn64874387]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_401215/ISPY2_401215_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 775M/775M [02:37<00:00, 4.92MB/s]

[syn64872873]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_402265/ISPY2_402265_0000.nii.gz

Downloading files: 100%|█████████▉| 775M/775M [02:37<00:00, 4.91MB/s]

[syn64872615]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_402384/ISPY2_402384_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 785M/785M [02:39<00:00, 4.93MB/s]

[syn64873447]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_405717/ISPY2_405717_0000.nii.gz

Downloading files: 100%|█████████▉| 785M/785M [02:39<00:00, 4.92MB/s]

[syn64881289]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_406190/ISPY2_406190_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 785M/785M [02:39<00:00, 4.91MB/s]

[syn64881815]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_407539/ISPY2_407539_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 785M/785M [02:40<00:00, 4.90MB/s]

[syn64877359]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_408692/ISPY2_408692_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 787M/787M [02:40<00:00, 4.89MB/s]

[syn64876337]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_409288/ISPY2_409288_0000.nii.gz

Downloading files: 100%|█████████▉| 787M/787M [02:41<00:00, 4.88MB/s]

[syn64871848]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_410083/ISPY2_410083_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 809M/809M [02:42<00:00, 4.97MB/s]

[syn64874716]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_411008/ISPY2_411008_0000.nii.gz

Downloading files: 100%|█████████▉| 818M/818M [02:43<00:00, 4.99MB/s]

[syn64871671]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_411684/ISPY2_411684_0000.nii.gz

Downloading files: 100%|█████████▉| 818M/818M [02:44<00:00, 4.98MB/s]

[syn64881208]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_411806/ISPY2_411806_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 839M/839M [02:45<00:00, 5.06MB/s]

[syn64874948]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_411950/ISPY2_411950_0000.nii.gz

Downloading files: 100%|█████████▉| 839M/839M [02:45<00:00, 5.06MB/s]

[syn64882705]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_412772/ISPY2_412772_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 839M/839M [02:46<00:00, 5.05MB/s]

[syn64873221]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_413211/ISPY2_413211_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 839M/839M [02:46<00:00, 5.04MB/s]

[syn64883254]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_413961/ISPY2_413961_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 839M/839M [02:46<00:00, 5.02MB/s]

[syn64877652]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_414256/ISPY2_414256_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 839M/839M [02:47<00:00, 5.02MB/s]

[syn64878296]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_414286/ISPY2_414286_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 839M/839M [02:47<00:00, 5.01MB/s]

[syn64878884]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_414844/ISPY2_414844_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 839M/839M [02:47<00:00, 5.00MB/s]

[syn64877050]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_414971/ISPY2_414971_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 839M/839M [02:48<00:00, 4.99MB/s]

[syn64883875]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_415039/ISPY2_415039_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 839M/839M [02:48<00:00, 4.97MB/s]

[syn64882969]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_416434/ISPY2_416434_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 843M/843M [02:49<00:00, 4.97MB/s]

[syn64872200]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_417474/ISPY2_417474_0000.nii.gz

Downloading files: 100%|█████████▉| 843M/843M [02:49<00:00, 4.96MB/s]

[syn64880797]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_417654/ISPY2_417654_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 865M/865M [02:51<00:00, 5.05MB/s]

[syn64872602]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_418593/ISPY2_418593_0000.nii.gz

Downloading files: 100%|█████████▉| 865M/865M [02:51<00:00, 5.04MB/s]

[syn64881029]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_419590/ISPY2_419590_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 874M/874M [02:52<00:00, 5.06MB/s]

[syn64875332]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_420523/ISPY2_420523_0000.nii.gz

Downloading files: 100%|█████████▉| 874M/874M [02:52<00:00, 5.05MB/s]

[syn64874230]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_421829/ISPY2_421829_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 878M/878M [02:53<00:00, 5.05MB/s]

[syn64882776]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_421917/ISPY2_421917_0000.nii.gz

Downloading files: 100%|█████████▉| 884M/884M [02:54<00:00, 5.06MB/s]

[syn64880654]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_422013/ISPY2_422013_0000.nii.gz

Downloading files: 100%|█████████▉| 884M/884M [02:55<00:00, 5.05MB/s]

[syn64879273]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_422450/ISPY2_422450_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 884M/884M [02:55<00:00, 5.04MB/s]

[syn64877811]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_422454/ISPY2_422454_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 884M/884M [02:55<00:00, 5.03MB/s]

[syn64883783]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_423619/ISPY2_423619_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 884M/884M [02:55<00:00, 5.02MB/s]

[syn64874969]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_423979/ISPY2_423979_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 884M/884M [02:56<00:00, 5.02MB/s]

[syn64877875]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_424541/ISPY2_424541_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 884M/884M [02:56<00:00, 5.01MB/s]

[syn64875472]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_425173/ISPY2_425173_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 884M/884M [02:56<00:00, 5.00MB/s]

[syn64873795]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_426106/ISPY2_426106_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 884M/884M [02:57<00:00, 4.99MB/s]

[syn64871986]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_427321/ISPY2_427321_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 889M/889M [02:58<00:00, 4.99MB/s]

[syn64882624]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_429220/ISPY2_429220_0000.nii.gz

Downloading files: 100%|█████████▉| 889M/889M [02:58<00:00, 4.98MB/s]

[syn64877891]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_430441/ISPY2_430441_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 893M/893M [02:59<00:00, 4.98MB/s]

[syn64873890]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_431061/ISPY2_431061_0000.nii.gz

Downloading files: 100%|█████████▉| 893M/893M [02:59<00:00, 4.97MB/s]

[syn64879088]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_432114/ISPY2_432114_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 893M/893M [02:59<00:00, 4.96MB/s]

[syn64882821]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_433144/ISPY2_433144_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 893M/893M [03:00<00:00, 4.95MB/s]

[syn64874875]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_435279/ISPY2_435279_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 893M/893M [03:00<00:00, 4.95MB/s]

[syn64871402]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_435313/ISPY2_435313_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 893M/893M [03:00<00:00, 4.94MB/s]

[syn64877492]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_436371/ISPY2_436371_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 902M/902M [03:01<00:00, 4.96MB/s]

[syn64880782]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_437162/ISPY2_437162_0000.nii.gz

Downloading files: 100%|█████████▉| 902M/902M [03:02<00:00, 4.95MB/s]

[syn64878521]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_437968/ISPY2_437968_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 907M/907M [03:03<00:00, 4.95MB/s]

[syn64879828]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_439489/ISPY2_439489_0000.nii.gz

Downloading files: 100%|█████████▉| 907M/907M [03:03<00:00, 4.94MB/s]

[syn64882710]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_442637/ISPY2_442637_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 911M/911M [03:04<00:00, 4.94MB/s]

[syn64883417]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_442669/ISPY2_442669_0000.nii.gz

Downloading files: 100%|█████████▉| 916M/916M [03:05<00:00, 4.95MB/s]

[syn64874744]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_442981/ISPY2_442981_0000.nii.gz

Downloading files: 100%|█████████▉| 924M/924M [03:06<00:00, 4.97MB/s]

[syn64881625]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_443444/ISPY2_443444_0000.nii.gz

Downloading files: 100%|█████████▉| 924M/924M [03:06<00:00, 4.96MB/s]

[syn64878602]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_443708/ISPY2_443708_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 928M/928M [03:07<00:00, 4.96MB/s]

[syn64879340]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_446263/ISPY2_446263_0000.nii.gz

Downloading files: 100%|█████████▉| 928M/928M [03:07<00:00, 4.95MB/s]

[syn64878187]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_451482/ISPY2_451482_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 928M/928M [03:07<00:00, 4.95MB/s]

[syn64871230]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_451816/ISPY2_451816_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 928M/928M [03:08<00:00, 4.94MB/s]

[syn64881687]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_452703/ISPY2_452703_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 933M/933M [03:08<00:00, 4.94MB/s]

[syn64877170]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_453596/ISPY2_453596_0000.nii.gz

Downloading files: 100%|█████████▉| 933M/933M [03:09<00:00, 4.93MB/s]

[syn64872745]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_454808/ISPY2_454808_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 936M/936M [03:09<00:00, 4.93MB/s]

[syn64878492]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_455828/ISPY2_455828_0000.nii.gz

Downloading files: 100%|█████████▉| 944M/944M [03:10<00:00, 4.94MB/s]

[syn64872123]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_456432/ISPY2_456432_0000.nii.gz

Downloading files: 100%|█████████▉| 944M/944M [03:11<00:00, 4.94MB/s]

[syn64882648]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_456506/ISPY2_456506_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 955M/955M [03:12<00:00, 4.96MB/s]

[syn64875784]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_458196/ISPY2_458196_0000.nii.gz

Downloading files: 100%|█████████▉| 955M/955M [03:12<00:00, 4.95MB/s]

[syn64882172]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_459311/ISPY2_459311_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 955M/955M [03:13<00:00, 4.94MB/s]

[syn64883169]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_460642/ISPY2_460642_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 957M/957M [03:14<00:00, 4.93MB/s]

[syn64872999]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_460776/ISPY2_460776_0000.nii.gz

Downloading files: 100%|█████████▉| 957M/957M [03:14<00:00, 4.93MB/s]

[syn64877286]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_460812/ISPY2_460812_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 961M/961M [03:15<00:00, 4.92MB/s]

[syn64875846]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_461824/ISPY2_461824_0000.nii.gz

Downloading files: 100%|█████████▉| 961M/961M [03:15<00:00, 4.91MB/s]

[syn64881695]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_462581/ISPY2_462581_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 966M/966M [03:16<00:00, 4.92MB/s]

[syn64877118]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_462582/ISPY2_462582_0000.nii.gz

Downloading files: 100%|█████████▉| 966M/966M [03:16<00:00, 4.91MB/s]

[syn64876898]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_462605/ISPY2_462605_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 966M/966M [03:17<00:00, 4.90MB/s]

[syn64876855]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_464547/ISPY2_464547_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 970M/970M [03:17<00:00, 4.90MB/s]

[syn64878051]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_465008/ISPY2_465008_0000.nii.gz

Downloading files: 100%|█████████▉| 970M/970M [03:18<00:00, 4.90MB/s]

[syn64875061]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_466267/ISPY2_466267_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 970M/970M [03:18<00:00, 4.89MB/s]

[syn64871961]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_467622/ISPY2_467622_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 970M/970M [03:18<00:00, 4.88MB/s]

[syn64874777]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_467686/ISPY2_467686_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 979M/979M [03:20<00:00, 4.89MB/s]

[syn64880490]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_472799/ISPY2_472799_0000.nii.gz

Downloading files: 100%|█████████▉| 979M/979M [03:20<00:00, 4.89MB/s]

[syn64881073]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_473365/ISPY2_473365_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 979M/979M [03:20<00:00, 4.88MB/s]

[syn64882192]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_473468/ISPY2_473468_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 979M/979M [03:21<00:00, 4.87MB/s]

[syn64875265]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_473505/ISPY2_473505_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 986M/986M [03:21<00:00, 4.88MB/s]

[syn64880594]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_474874/ISPY2_474874_0000.nii.gz

Downloading files: 100%|█████████▉| 986M/986M [03:22<00:00, 4.88MB/s]

[syn64871619]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_477816/ISPY2_477816_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 986M/986M [03:22<00:00, 4.87MB/s]

[syn64883814]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_477994/ISPY2_477994_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 986M/986M [03:22<00:00, 4.86MB/s]

[syn64883120]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_478055/ISPY2_478055_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 991M/991M [03:23<00:00, 4.86MB/s]

[syn64880985]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_478484/ISPY2_478484_0000.nii.gz

Downloading files: 100%|█████████▉| 1.00G/1.00G [03:25<00:00, 4.88MB/s]

[syn64881884]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_478655/ISPY2_478655_0000.nii.gz

Downloading files: 100%|█████████▉| 1.00G/1.00G [03:26<00:00, 4.88MB/s]

[syn64872184]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_479417/ISPY2_479417_0000.nii.gz

Downloading files: 100%|█████████▉| 1.00G/1.00G [03:26<00:00, 4.87MB/s]

[syn64882784]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_483667/ISPY2_483667_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.00G/1.00G [03:26<00:00, 4.86MB/s]

[syn64876167]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_483910/ISPY2_483910_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.00G/1.00G [03:27<00:00, 4.85MB/s]

[syn64881395]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_484867/ISPY2_484867_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.00G/1.00G [03:27<00:00, 4.85MB/s]

[syn64874145]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_484894/ISPY2_484894_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.02G/1.02G [03:28<00:00, 4.87MB/s]

[syn64876779]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_485637/ISPY2_485637_0000.nii.gz

Downloading files: 100%|█████████▉| 1.02G/1.02G [03:29<00:00, 4.87MB/s]

[syn64876379]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_489194/ISPY2_489194_0000.nii.gz

Downloading files: 100%|█████████▉| 1.02G/1.02G [03:30<00:00, 4.87MB/s]

[syn64873248]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_489504/ISPY2_489504_0000.nii.gz

Downloading files: 100%|█████████▉| 1.03G/1.03G [03:31<00:00, 4.87MB/s]

[syn64881189]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_489973/ISPY2_489973_0000.nii.gz

Downloading files: 100%|█████████▉| 1.03G/1.03G [03:31<00:00, 4.88MB/s]

[syn64872955]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_490023/ISPY2_490023_0000.nii.gz

Downloading files: 100%|█████████▉| 1.03G/1.03G [03:32<00:00, 4.87MB/s]

[syn64882792]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_490805/ISPY2_490805_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.03G/1.03G [03:32<00:00, 4.86MB/s]

[syn64878988]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_491526/ISPY2_491526_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.03G/1.03G [03:32<00:00, 4.85MB/s]

[syn64874370]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_491779/ISPY2_491779_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.03G/1.03G [03:33<00:00, 4.85MB/s]

[syn64883644]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_492612/ISPY2_492612_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.03G/1.03G [03:33<00:00, 4.84MB/s]

[syn64875941]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_493472/ISPY2_493472_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.05G/1.05G [03:34<00:00, 4.90MB/s]

[syn64878815]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_493519/ISPY2_493519_0000.nii.gz

Downloading files: 100%|█████████▉| 1.06G/1.06G [03:35<00:00, 4.90MB/s]

[syn64871484]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_493775/ISPY2_493775_0000.nii.gz

Downloading files: 100%|█████████▉| 1.06G/1.06G [03:36<00:00, 4.90MB/s]

[syn64872506]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_494022/ISPY2_494022_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.06G/1.06G [03:36<00:00, 4.89MB/s]

[syn64873461]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_494296/ISPY2_494296_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.06G/1.06G [03:37<00:00, 4.89MB/s]

[syn64872298]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_494946/ISPY2_494946_0000.nii.gz

Downloading files: 100%|█████████▉| 1.06G/1.06G [03:37<00:00, 4.89MB/s]

[syn64876890]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_495440/ISPY2_495440_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.06G/1.06G [03:37<00:00, 4.88MB/s]

[syn64881093]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_496205/ISPY2_496205_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.07G/1.07G [03:38<00:00, 4.88MB/s]

[syn64873267]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_497010/ISPY2_497010_0000.nii.gz

Downloading files: 100%|█████████▉| 1.07G/1.07G [03:39<00:00, 4.87MB/s]

[syn64877698]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_498024/ISPY2_498024_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.07G/1.07G [03:39<00:00, 4.87MB/s]

[syn64881586]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_498985/ISPY2_498985_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.07G/1.07G [03:39<00:00, 4.86MB/s]

[syn64878646]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_500826/ISPY2_500826_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.07G/1.07G [03:39<00:00, 4.85MB/s]

[syn64879931]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_501303/ISPY2_501303_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.07G/1.07G [03:40<00:00, 4.85MB/s]

[syn64878734]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_502486/ISPY2_502486_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.07G/1.07G [03:41<00:00, 4.85MB/s]

[syn64881854]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_503034/ISPY2_503034_0000.nii.gz

Downloading files: 100%|█████████▉| 1.07G/1.07G [03:41<00:00, 4.84MB/s]

[syn64877530]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_504838/ISPY2_504838_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.07G/1.07G [03:41<00:00, 4.83MB/s]

[syn64883625]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_506623/ISPY2_506623_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.08G/1.08G [03:42<00:00, 4.85MB/s]

[syn64872752]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_507198/ISPY2_507198_0000.nii.gz

Downloading files: 100%|█████████▉| 1.08G/1.08G [03:42<00:00, 4.84MB/s]

[syn64881540]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_507249/ISPY2_507249_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.08G/1.08G [03:43<00:00, 4.83MB/s]

[syn64872036]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_509012/ISPY2_509012_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.08G/1.08G [03:43<00:00, 4.83MB/s]

[syn64879756]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_510543/ISPY2_510543_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.08G/1.08G [03:43<00:00, 4.82MB/s]

[syn64880004]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_511851/ISPY2_511851_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.09G/1.09G [03:45<00:00, 4.84MB/s]

[syn64871583]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_515105/ISPY2_515105_0000.nii.gz

Downloading files: 100%|█████████▉| 1.10G/1.10G [03:46<00:00, 4.87MB/s]

[syn64871299]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_515141/ISPY2_515141_0000.nii.gz

Downloading files: 100%|█████████▉| 1.10G/1.10G [03:46<00:00, 4.86MB/s]

[syn64873253]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_515281/ISPY2_515281_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.12G/1.12G [03:48<00:00, 4.92MB/s]

[syn64878338]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_515284/ISPY2_515284_0000.nii.gz

Downloading files: 100%|█████████▉| 1.12G/1.12G [03:48<00:00, 4.91MB/s]

[syn64878425]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_515565/ISPY2_515565_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.13G/1.13G [03:49<00:00, 4.92MB/s]

[syn64876300]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_516763/ISPY2_516763_0000.nii.gz

Downloading files: 100%|█████████▉| 1.13G/1.13G [03:50<00:00, 4.92MB/s]

[syn64879096]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_516834/ISPY2_516834_0000.nii.gz

Downloading files: 100%|█████████▉| 1.14G/1.14G [03:51<00:00, 4.93MB/s]

[syn64876844]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_517446/ISPY2_517446_0000.nii.gz

Downloading files: 100%|█████████▉| 1.14G/1.14G [03:51<00:00, 4.92MB/s]

[syn64874097]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_517870/ISPY2_517870_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.14G/1.14G [03:52<00:00, 4.91MB/s]

[syn64879678]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_518000/ISPY2_518000_0000.nii.gz

Downloading files: 100%|█████████▉| 1.15G/1.15G [03:53<00:00, 4.92MB/s]

[syn64881407]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_518576/ISPY2_518576_0000.nii.gz

Downloading files: 100%|█████████▉| 1.15G/1.15G [03:54<00:00, 4.92MB/s]

[syn64880509]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_519738/ISPY2_519738_0000.nii.gz

Downloading files: 100%|█████████▉| 1.15G/1.15G [03:54<00:00, 4.91MB/s]

[syn64881570]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_520258/ISPY2_520258_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.17G/1.17G [03:55<00:00, 4.97MB/s]

[syn64878846]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_520471/ISPY2_520471_0000.nii.gz

Downloading files: 100%|█████████▉| 1.17G/1.17G [03:56<00:00, 4.96MB/s]

[syn64874786]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_520986/ISPY2_520986_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.18G/1.18G [03:57<00:00, 4.97MB/s]

[syn64879566]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_521860/ISPY2_521860_0000.nii.gz

Downloading files: 100%|█████████▉| 1.18G/1.18G [03:57<00:00, 4.96MB/s]

[syn64871130]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_522140/ISPY2_522140_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.18G/1.18G [03:57<00:00, 4.96MB/s]

[syn64878487]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_524170/ISPY2_524170_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.18G/1.18G [03:57<00:00, 4.95MB/s]

[syn64883227]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_527320/ISPY2_527320_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.19G/1.19G [03:59<00:00, 4.99MB/s]

[syn64873678]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_527581/ISPY2_527581_0000.nii.gz

Downloading files: 100%|█████████▉| 1.20G/1.20G [04:00<00:00, 4.99MB/s]

[syn64882652]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_528479/ISPY2_528479_0000.nii.gz

Downloading files: 100%|█████████▉| 1.20G/1.20G [04:00<00:00, 4.98MB/s]

[syn64876419]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_528833/ISPY2_528833_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.20G/1.20G [04:01<00:00, 4.98MB/s]

[syn64882256]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_530095/ISPY2_530095_0000.nii.gz

Downloading files: 100%|█████████▉| 1.20G/1.20G [04:01<00:00, 4.97MB/s]

[syn64876153]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_531672/ISPY2_531672_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.20G/1.20G [04:01<00:00, 4.97MB/s]

[syn64878662]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_531988/ISPY2_531988_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.20G/1.20G [04:02<00:00, 4.96MB/s]

[syn64875654]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_532183/ISPY2_532183_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.20G/1.20G [04:02<00:00, 4.96MB/s]

[syn64873048]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_535415/ISPY2_535415_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.20G/1.20G [04:02<00:00, 4.95MB/s]

[syn64878999]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_535569/ISPY2_535569_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.20G/1.20G [04:03<00:00, 4.95MB/s]

[syn64874748]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_535779/ISPY2_535779_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.20G/1.20G [04:03<00:00, 4.94MB/s]

[syn64874800]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_536253/ISPY2_536253_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.21G/1.21G [04:04<00:00, 4.95MB/s]

[syn64883588]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_539291/ISPY2_539291_0000.nii.gz

Downloading files: 100%|█████████▉| 1.21G/1.21G [04:05<00:00, 4.94MB/s]

[syn64879487]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_539876/ISPY2_539876_0000.nii.gz

Downloading files: 100%|█████████▉| 1.22G/1.22G [04:05<00:00, 4.95MB/s]

[syn64876452]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_539904/ISPY2_539904_0000.nii.gz

Downloading files: 100%|█████████▉| 1.22G/1.22G [04:06<00:00, 4.94MB/s]

[syn64878143]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_540539/ISPY2_540539_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.22G/1.22G [04:06<00:00, 4.93MB/s]

[syn64883721]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_541165/ISPY2_541165_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.24G/1.24G [04:08<00:00, 4.99MB/s]

[syn64883150]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_542392/ISPY2_542392_0000.nii.gz

Downloading files: 100%|█████████▉| 1.24G/1.24G [04:08<00:00, 4.98MB/s]

[syn64878699]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_543795/ISPY2_543795_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.24G/1.24G [04:09<00:00, 4.98MB/s]

[syn64874676]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_547892/ISPY2_547892_0000.nii.gz

Downloading files: 100%|█████████▉| 1.24G/1.24G [04:09<00:00, 4.98MB/s]

[syn64883887]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_549172/ISPY2_549172_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.24G/1.24G [04:09<00:00, 4.97MB/s]

[syn64883558]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_550157/ISPY2_550157_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.25G/1.25G [04:10<00:00, 4.98MB/s]

[syn64881808]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_550421/ISPY2_550421_0000.nii.gz

Downloading files: 100%|█████████▉| 1.25G/1.25G [04:11<00:00, 4.98MB/s]

[syn64880918]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_551795/ISPY2_551795_0000.nii.gz

Downloading files: 100%|█████████▉| 1.25G/1.25G [04:12<00:00, 4.97MB/s]

[syn64882808]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_552313/ISPY2_552313_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.26G/1.26G [04:13<00:00, 4.97MB/s]

[syn64883527]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_552549/ISPY2_552549_0000.nii.gz

Downloading files: 100%|█████████▉| 1.26G/1.26G [04:13<00:00, 4.97MB/s]

[syn64872781]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_553012/ISPY2_553012_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.26G/1.26G [04:13<00:00, 4.96MB/s]

[syn64874528]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_553141/ISPY2_553141_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.26G/1.26G [04:13<00:00, 4.96MB/s]

[syn64880760]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_554577/ISPY2_554577_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.26G/1.26G [04:14<00:00, 4.95MB/s]

[syn64876791]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_555214/ISPY2_555214_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.26G/1.26G [04:14<00:00, 4.95MB/s]

[syn64876005]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_559021/ISPY2_559021_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.26G/1.26G [04:14<00:00, 4.94MB/s]

[syn64881258]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_559263/ISPY2_559263_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.26G/1.26G [04:15<00:00, 4.93MB/s]

[syn64874271]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_563681/ISPY2_563681_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.26G/1.26G [04:15<00:00, 4.93MB/s]

[syn64878507]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_563856/ISPY2_563856_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.26G/1.26G [04:15<00:00, 4.92MB/s]

[syn64872253]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_564234/ISPY2_564234_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.26G/1.26G [04:16<00:00, 4.92MB/s]

[syn64880358]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_564701/ISPY2_564701_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.26G/1.26G [04:16<00:00, 4.92MB/s]

[syn64879263]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_566011/ISPY2_566011_0000.nii.gz

Downloading files: 100%|█████████▉| 1.26G/1.26G [04:17<00:00, 4.91MB/s]

[syn64883058]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_567201/ISPY2_567201_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.26G/1.26G [04:17<00:00, 4.91MB/s]

[syn64874298]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_567907/ISPY2_567907_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.26G/1.26G [04:17<00:00, 4.90MB/s]

[syn64882213]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_568331/ISPY2_568331_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.27G/1.27G [04:18<00:00, 4.90MB/s]

[syn64878916]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_568953/ISPY2_568953_0000.nii.gz

Downloading files: 100%|█████████▉| 1.27G/1.27G [04:19<00:00, 4.90MB/s]

[syn64871788]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_570148/ISPY2_570148_0000.nii.gz

Downloading files: 100%|█████████▉| 1.28G/1.28G [04:20<00:00, 4.91MB/s]

[syn64882239]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_570380/ISPY2_570380_0000.nii.gz

Downloading files: 100%|█████████▉| 1.28G/1.28G [04:21<00:00, 4.91MB/s]

[syn64872345]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_570685/ISPY2_570685_0000.nii.gz

Downloading files: 100%|█████████▉| 1.28G/1.28G [04:21<00:00, 4.90MB/s]

[syn64880993]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_570966/ISPY2_570966_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.28G/1.28G [04:22<00:00, 4.89MB/s]

[syn64883165]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_571276/ISPY2_571276_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.29G/1.29G [04:23<00:00, 4.90MB/s]

[syn64872468]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_571995/ISPY2_571995_0000.nii.gz

Downloading files: 100%|█████████▉| 1.29G/1.29G [04:23<00:00, 4.89MB/s]

[syn64874661]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_572016/ISPY2_572016_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.29G/1.29G [04:23<00:00, 4.88MB/s]

[syn64873303]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_572235/ISPY2_572235_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.29G/1.29G [04:24<00:00, 4.88MB/s]

[syn64873071]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_572444/ISPY2_572444_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.29G/1.29G [04:24<00:00, 4.87MB/s]

[syn64881635]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_572731/ISPY2_572731_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.29G/1.29G [04:24<00:00, 4.87MB/s]

[syn64875560]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_572793/ISPY2_572793_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.29G/1.29G [04:25<00:00, 4.86MB/s]

[syn64879425]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_573586/ISPY2_573586_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.29G/1.29G [04:25<00:00, 4.86MB/s]

[syn64882551]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_573605/ISPY2_573605_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.31G/1.31G [04:26<00:00, 4.91MB/s]

[syn64871161]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_573881/ISPY2_573881_0000.nii.gz

Downloading files: 100%|█████████▉| 1.32G/1.32G [04:27<00:00, 4.91MB/s]

[syn64873484]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_573919/ISPY2_573919_0000.nii.gz

Downloading files: 100%|█████████▉| 1.32G/1.32G [04:28<00:00, 4.91MB/s]

[syn64881334]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_574091/ISPY2_574091_0000.nii.gz

Downloading files: 100%|█████████▉| 1.32G/1.32G [04:29<00:00, 4.91MB/s]

[syn64872689]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_575372/ISPY2_575372_0000.nii.gz

Downloading files: 100%|█████████▉| 1.33G/1.33G [04:30<00:00, 4.91MB/s]

[syn64871760]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_575457/ISPY2_575457_0000.nii.gz

Downloading files: 100%|█████████▉| 1.33G/1.33G [04:30<00:00, 4.90MB/s]

[syn64883683]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_578975/ISPY2_578975_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.33G/1.33G [04:31<00:00, 4.90MB/s]

[syn64873989]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_579881/ISPY2_579881_0000.nii.gz

Downloading files: 100%|█████████▉| 1.33G/1.33G [04:31<00:00, 4.90MB/s]

[syn64880647]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_580541/ISPY2_580541_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.34G/1.34G [04:32<00:00, 4.90MB/s]

[syn64879064]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_580632/ISPY2_580632_0000.nii.gz

Downloading files: 100%|█████████▉| 1.34G/1.34G [04:32<00:00, 4.90MB/s]

[syn64880069]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_581648/ISPY2_581648_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.34G/1.34G [04:33<00:00, 4.89MB/s]

[syn64876548]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_584561/ISPY2_584561_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.34G/1.34G [04:33<00:00, 4.89MB/s]

[syn64882086]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_586091/ISPY2_586091_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.34G/1.34G [04:33<00:00, 4.88MB/s]

[syn64883497]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_586207/ISPY2_586207_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.34G/1.34G [04:34<00:00, 4.87MB/s]

[syn64871322]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_587388/ISPY2_587388_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.35G/1.35G [04:35<00:00, 4.90MB/s]

[syn64879638]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_587604/ISPY2_587604_0000.nii.gz

Downloading files: 100%|█████████▉| 1.35G/1.35G [04:36<00:00, 4.90MB/s]

[syn64871897]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_587691/ISPY2_587691_0000.nii.gz

Downloading files: 100%|█████████▉| 1.35G/1.35G [04:36<00:00, 4.89MB/s]

[syn64880559]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_589502/ISPY2_589502_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.36G/1.36G [04:38<00:00, 4.90MB/s]

[syn64883553]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_590220/ISPY2_590220_0000.nii.gz

Downloading files: 100%|█████████▉| 1.36G/1.36G [04:38<00:00, 4.90MB/s]

[syn64875812]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_590299/ISPY2_590299_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.36G/1.36G [04:38<00:00, 4.89MB/s]

[syn64879631]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_591079/ISPY2_591079_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.37G/1.37G [04:39<00:00, 4.89MB/s]

[syn64874076]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_591180/ISPY2_591180_0000.nii.gz

Downloading files: 100%|█████████▉| 1.37G/1.37G [04:40<00:00, 4.89MB/s]

[syn64873745]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_591810/ISPY2_591810_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.37G/1.37G [04:40<00:00, 4.88MB/s]

[syn64882564]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_592535/ISPY2_592535_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.39G/1.39G [04:41<00:00, 4.93MB/s]

[syn64872575]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_596079/ISPY2_596079_0000.nii.gz

Downloading files: 100%|█████████▉| 1.39G/1.39G [04:42<00:00, 4.93MB/s]

[syn64880092]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_596458/ISPY2_596458_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.39G/1.39G [04:42<00:00, 4.92MB/s]

[syn64882939]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_597253/ISPY2_597253_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.40G/1.40G [04:43<00:00, 4.92MB/s]

[syn64879808]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_597873/ISPY2_597873_0000.nii.gz

Downloading files: 100%|█████████▉| 1.40G/1.40G [04:43<00:00, 4.92MB/s]

[syn64875125]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_597907/ISPY2_597907_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.40G/1.40G [04:44<00:00, 4.91MB/s]

[syn64881958]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_598798/ISPY2_598798_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.40G/1.40G [04:44<00:00, 4.91MB/s]

[syn64881981]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_598835/ISPY2_598835_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.40G/1.40G [04:44<00:00, 4.90MB/s]

[syn64878317]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_600536/ISPY2_600536_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.40G/1.40G [04:45<00:00, 4.89MB/s]

[syn64879329]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_601489/ISPY2_601489_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.40G/1.40G [04:45<00:00, 4.89MB/s]

[syn64880108]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_602451/ISPY2_602451_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.40G/1.40G [04:45<00:00, 4.88MB/s]

[syn64874847]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_602943/ISPY2_602943_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.40G/1.40G [04:46<00:00, 4.88MB/s]

[syn64876570]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_604199/ISPY2_604199_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.40G/1.40G [04:46<00:00, 4.87MB/s]

[syn64883359]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_604326/ISPY2_604326_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.40G/1.40G [04:47<00:00, 4.87MB/s]

[syn64883019]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_604380/ISPY2_604380_0000.nii.gz

Downloading files: 100%|█████████▉| 1.41G/1.41G [04:48<00:00, 4.88MB/s]

[syn64878591]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_605713/ISPY2_605713_0000.nii.gz

Downloading files: 100%|█████████▉| 1.41G/1.41G [04:48<00:00, 4.87MB/s]

[syn64878306]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_607047/ISPY2_607047_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.41G/1.41G [04:48<00:00, 4.87MB/s]

[syn64873645]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_607843/ISPY2_607843_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.41G/1.41G [04:49<00:00, 4.87MB/s]

[syn64880364]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_609151/ISPY2_609151_0000.nii.gz

Downloading files: 100%|█████████▉| 1.41G/1.41G [04:49<00:00, 4.86MB/s]

[syn64874038]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_609642/ISPY2_609642_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.41G/1.41G [04:50<00:00, 4.86MB/s]

[syn64878834]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_609897/ISPY2_609897_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.41G/1.41G [04:50<00:00, 4.85MB/s]

[syn64879387]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_611662/ISPY2_611662_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.41G/1.41G [04:51<00:00, 4.85MB/s]

[syn64881867]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_613188/ISPY2_613188_0000.nii.gz

Downloading files: 100%|█████████▉| 1.42G/1.42G [04:52<00:00, 4.85MB/s]

[syn64883751]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_613961/ISPY2_613961_0000.nii.gz

Downloading files: 100%|█████████▉| 1.42G/1.42G [04:53<00:00, 4.85MB/s]

[syn64879881]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_614044/ISPY2_614044_0000.nii.gz

Downloading files: 100%|█████████▉| 1.42G/1.42G [04:53<00:00, 4.85MB/s]

[syn64874920]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_614434/ISPY2_614434_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.42G/1.42G [04:53<00:00, 4.85MB/s]

[syn64878766]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_615873/ISPY2_615873_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.42G/1.42G [04:54<00:00, 4.84MB/s]

[syn64872930]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_616994/ISPY2_616994_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.44G/1.44G [04:55<00:00, 4.87MB/s]

[syn64880463]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_618240/ISPY2_618240_0000.nii.gz

Downloading files: 100%|█████████▉| 1.45G/1.45G [04:56<00:00, 4.88MB/s]

[syn64875726]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_618717/ISPY2_618717_0000.nii.gz

Downloading files: 100%|█████████▉| 1.45G/1.45G [04:56<00:00, 4.88MB/s]

[syn64878631]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_618860/ISPY2_618860_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.45G/1.45G [04:57<00:00, 4.87MB/s]

[syn64875871]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_621179/ISPY2_621179_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.45G/1.45G [04:57<00:00, 4.87MB/s]

[syn64882454]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_622078/ISPY2_622078_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.45G/1.45G [04:58<00:00, 4.87MB/s]

[syn64875849]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_622315/ISPY2_622315_0000.nii.gz

Downloading files: 100%|█████████▉| 1.45G/1.45G [04:58<00:00, 4.86MB/s]

[syn64878547]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_622688/ISPY2_622688_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.46G/1.46G [04:59<00:00, 4.87MB/s]

[syn64881282]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_623086/ISPY2_623086_0000.nii.gz

Downloading files: 100%|█████████▉| 1.46G/1.46G [05:00<00:00, 4.87MB/s]

[syn64880824]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_623569/ISPY2_623569_0000.nii.gz

Downloading files: 100%|█████████▉| 1.47G/1.47G [05:01<00:00, 4.88MB/s]

[syn64880677]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_624777/ISPY2_624777_0000.nii.gz

Downloading files: 100%|█████████▉| 1.47G/1.47G [05:02<00:00, 4.88MB/s]

[syn64878435]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_625800/ISPY2_625800_0000.nii.gz

Downloading files: 100%|█████████▉| 1.47G/1.47G [05:02<00:00, 4.88MB/s]

[syn64880333]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_625854/ISPY2_625854_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.48G/1.48G [05:03<00:00, 4.88MB/s]

[syn64879592]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_627118/ISPY2_627118_0000.nii.gz

Downloading files: 100%|█████████▉| 1.50G/1.50G [05:04<00:00, 4.93MB/s]

[syn64879868]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_627981/ISPY2_627981_0000.nii.gz

Downloading files: 100%|█████████▉| 1.50G/1.50G [05:05<00:00, 4.92MB/s]

[syn64880499]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_628692/ISPY2_628692_0000.nii.gz

Downloading files: 100%|█████████▉| 1.51G/1.51G [05:06<00:00, 4.93MB/s]

[syn64881759]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_628788/ISPY2_628788_0000.nii.gz

Downloading files: 100%|█████████▉| 1.51G/1.51G [05:07<00:00, 4.92MB/s]

[syn64880233]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_628823/ISPY2_628823_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.52G/1.52G [05:08<00:00, 4.93MB/s]

[syn64877453]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_629210/ISPY2_629210_0000.nii.gz

Downloading files: 100%|█████████▉| 1.52G/1.52G [05:09<00:00, 4.93MB/s]

[syn64883727]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_629371/ISPY2_629371_0000.nii.gz

Downloading files: 100%|█████████▉| 1.52G/1.52G [05:09<00:00, 4.92MB/s]

[syn64878409]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_629606/ISPY2_629606_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.52G/1.52G [05:09<00:00, 4.92MB/s]

[syn64883390]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_630758/ISPY2_630758_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.52G/1.52G [05:09<00:00, 4.91MB/s]

[syn64880375]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_631299/ISPY2_631299_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.54G/1.54G [05:11<00:00, 4.94MB/s]

[syn64881179]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_631337/ISPY2_631337_0000.nii.gz

Downloading files: 100%|█████████▉| 1.55G/1.55G [05:12<00:00, 4.94MB/s]

[syn64881934]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_632408/ISPY2_632408_0000.nii.gz

Downloading files: 100%|█████████▉| 1.55G/1.55G [05:13<00:00, 4.94MB/s]

[syn64879762]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_635632/ISPY2_635632_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.55G/1.55G [05:13<00:00, 4.93MB/s]

[syn64879511]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_635862/ISPY2_635862_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.55G/1.55G [05:14<00:00, 4.93MB/s]

[syn64882596]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_636424/ISPY2_636424_0000.nii.gz

Downloading files: 100%|█████████▉| 1.55G/1.55G [05:14<00:00, 4.93MB/s]

[syn64874736]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_637051/ISPY2_637051_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.55G/1.55G [05:14<00:00, 4.92MB/s]

[syn64881529]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_637566/ISPY2_637566_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.55G/1.55G [05:15<00:00, 4.92MB/s]

[syn64879854]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_637752/ISPY2_637752_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.55G/1.55G [05:15<00:00, 4.91MB/s]

[syn64879521]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_638126/ISPY2_638126_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.56G/1.56G [05:16<00:00, 4.92MB/s]

[syn64879530]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_639663/ISPY2_639663_0000.nii.gz

Downloading files: 100%|█████████▉| 1.56G/1.56G [05:16<00:00, 4.92MB/s]

[syn64872546]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_640043/ISPY2_640043_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.56G/1.56G [05:17<00:00, 4.92MB/s]

[syn64880419]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_640463/ISPY2_640463_0000.nii.gz

Downloading files: 100%|█████████▉| 1.57G/1.57G [05:18<00:00, 4.92MB/s]

[syn64880911]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_640927/ISPY2_640927_0000.nii.gz

Downloading files: 100%|█████████▉| 1.59G/1.59G [05:19<00:00, 4.97MB/s]

[syn64882142]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_641246/ISPY2_641246_0000.nii.gz

Downloading files: 100%|█████████▉| 1.59G/1.59G [05:20<00:00, 4.97MB/s]

[syn64878683]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_641697/ISPY2_641697_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.60G/1.60G [05:21<00:00, 4.97MB/s]

[syn64875024]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_641977/ISPY2_641977_0000.nii.gz

Downloading files: 100%|█████████▉| 1.60G/1.60G [05:21<00:00, 4.96MB/s]

[syn64874182]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_644186/ISPY2_644186_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.60G/1.60G [05:21<00:00, 4.96MB/s]

[syn64876535]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_644609/ISPY2_644609_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.60G/1.60G [05:22<00:00, 4.95MB/s]

[syn64873570]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_646233/ISPY2_646233_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.60G/1.60G [05:23<00:00, 4.95MB/s]

[syn64882462]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_646600/ISPY2_646600_0000.nii.gz

Downloading files: 100%|█████████▉| 1.60G/1.60G [05:23<00:00, 4.95MB/s]

[syn64879020]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_649198/ISPY2_649198_0000.nii.gz

Downloading files: 100%|█████████▉| 1.60G/1.60G [05:24<00:00, 4.95MB/s]

[syn64879884]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_650589/ISPY2_650589_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.60G/1.60G [05:24<00:00, 4.94MB/s]

[syn64876431]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_651145/ISPY2_651145_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.61G/1.61G [05:25<00:00, 4.94MB/s]

[syn64880948]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_651401/ISPY2_651401_0000.nii.gz

Downloading files: 100%|█████████▉| 1.61G/1.61G [05:25<00:00, 4.93MB/s]

[syn64871953]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_651541/ISPY2_651541_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.61G/1.61G [05:26<00:00, 4.94MB/s]

[syn64883831]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_652480/ISPY2_652480_0000.nii.gz

Downloading files: 100%|█████████▉| 1.62G/1.62G [05:27<00:00, 4.94MB/s]

[syn64872399]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_653325/ISPY2_653325_0000.nii.gz

Downloading files: 100%|█████████▉| 1.62G/1.62G [05:28<00:00, 4.94MB/s]

[syn64876366]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_653927/ISPY2_653927_0000.nii.gz

Downloading files: 100%|█████████▉| 1.62G/1.62G [05:28<00:00, 4.94MB/s]

[syn64881945]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_654021/ISPY2_654021_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.62G/1.62G [05:29<00:00, 4.93MB/s]

[syn64883136]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_654064/ISPY2_654064_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.63G/1.63G [05:30<00:00, 4.94MB/s]

[syn64877623]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_654956/ISPY2_654956_0000.nii.gz

Downloading files: 100%|█████████▉| 1.63G/1.63G [05:30<00:00, 4.94MB/s]

[syn64877441]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_655128/ISPY2_655128_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.63G/1.63G [05:31<00:00, 4.93MB/s]

[syn64871546]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_655703/ISPY2_655703_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.63G/1.63G [05:31<00:00, 4.93MB/s]

[syn64872104]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_655795/ISPY2_655795_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.63G/1.63G [05:31<00:00, 4.92MB/s]

[syn64875705]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_658541/ISPY2_658541_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.64G/1.64G [05:32<00:00, 4.92MB/s]

[syn64877062]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_660534/ISPY2_660534_0000.nii.gz

Downloading files: 100%|█████████▉| 1.64G/1.64G [05:32<00:00, 4.92MB/s]

[syn64874281]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_660915/ISPY2_660915_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.64G/1.64G [05:33<00:00, 4.92MB/s]

[syn64873980]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_661730/ISPY2_661730_0000.nii.gz

Downloading files: 100%|█████████▉| 1.65G/1.65G [05:34<00:00, 4.92MB/s]

[syn64883321]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_663144/ISPY2_663144_0000.nii.gz

Downloading files: 100%|█████████▉| 1.65G/1.65G [05:35<00:00, 4.92MB/s]

[syn64873771]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_663197/ISPY2_663197_0000.nii.gz

Downloading files: 100%|█████████▉| 1.65G/1.65G [05:35<00:00, 4.91MB/s]

[syn64883881]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_663467/ISPY2_663467_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.65G/1.65G [05:36<00:00, 4.91MB/s]

[syn64880957]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_664111/ISPY2_664111_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.66G/1.66G [05:37<00:00, 4.92MB/s]

[syn64876746]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_664658/ISPY2_664658_0000.nii.gz

Downloading files: 100%|█████████▉| 1.67G/1.67G [05:38<00:00, 4.94MB/s]

[syn64882368]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_666147/ISPY2_666147_0000.nii.gz

Downloading files: 100%|█████████▉| 1.68G/1.68G [05:39<00:00, 4.94MB/s]

[syn64879834]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_666450/ISPY2_666450_0000.nii.gz

Downloading files: 100%|█████████▉| 1.69G/1.69G [05:40<00:00, 4.95MB/s]

[syn64881184]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_666715/ISPY2_666715_0000.nii.gz

Downloading files: 100%|█████████▉| 1.70G/1.70G [05:41<00:00, 4.96MB/s]

[syn64883519]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_668752/ISPY2_668752_0000.nii.gz

Downloading files: 100%|█████████▉| 1.70G/1.70G [05:42<00:00, 4.96MB/s]

[syn64872674]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_672734/ISPY2_672734_0000.nii.gz

Downloading files: 100%|█████████▉| 1.70G/1.70G [05:43<00:00, 4.96MB/s]

[syn64882031]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_674897/ISPY2_674897_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.70G/1.70G [05:43<00:00, 4.96MB/s]

[syn64881109]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_676048/ISPY2_676048_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.72G/1.72G [05:44<00:00, 4.98MB/s]

[syn64880158]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_676365/ISPY2_676365_0000.nii.gz

Downloading files: 100%|█████████▉| 1.73G/1.73G [05:45<00:00, 5.00MB/s]

[syn64875587]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_676630/ISPY2_676630_0000.nii.gz

Downloading files: 100%|█████████▉| 1.74G/1.74G [05:46<00:00, 5.01MB/s]

[syn64883744]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_677910/ISPY2_677910_0000.nii.gz

Downloading files: 100%|█████████▉| 1.74G/1.74G [05:47<00:00, 5.00MB/s]

[syn64877010]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_677915/ISPY2_677915_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.74G/1.74G [05:47<00:00, 5.00MB/s]

[syn64879662]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_679787/ISPY2_679787_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.74G/1.74G [05:48<00:00, 5.01MB/s]

[syn64876349]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_680881/ISPY2_680881_0000.nii.gz

Downloading files: 100%|█████████▉| 1.75G/1.75G [05:48<00:00, 5.01MB/s]

[syn64874314]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_683173/ISPY2_683173_0000.nii.gz

Downloading files: 100%|█████████▉| 1.76G/1.76G [05:50<00:00, 5.02MB/s]

[syn64871144]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_683374/ISPY2_683374_0000.nii.gz

Downloading files: 100%|█████████▉| 1.77G/1.77G [05:51<00:00, 5.04MB/s]

[syn64880309]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_683457/ISPY2_683457_0000.nii.gz

Downloading files: 100%|█████████▉| 1.77G/1.77G [05:52<00:00, 5.04MB/s]

[syn64874987]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_683896/ISPY2_683896_0000.nii.gz

Downloading files: 100%|█████████▉| 1.78G/1.78G [05:52<00:00, 5.04MB/s]

[syn64882371]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_685182/ISPY2_685182_0000.nii.gz

Downloading files: 100%|█████████▉| 1.78G/1.78G [05:53<00:00, 5.03MB/s]

[syn64883734]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_685753/ISPY2_685753_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.78G/1.78G [05:53<00:00, 5.03MB/s]

[syn64873524]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_685795/ISPY2_685795_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.78G/1.78G [05:53<00:00, 5.02MB/s]

[syn64876275]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_687288/ISPY2_687288_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.78G/1.78G [05:54<00:00, 5.02MB/s]

[syn64880586]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_687733/ISPY2_687733_0000.nii.gz

Downloading files: 100%|█████████▉| 1.78G/1.78G [05:55<00:00, 5.02MB/s]

[syn64880995]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_688291/ISPY2_688291_0000.nii.gz

Downloading files: 100%|█████████▉| 1.78G/1.78G [05:55<00:00, 5.02MB/s]

[syn64880698]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_688955/ISPY2_688955_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.79G/1.79G [05:56<00:00, 5.01MB/s]

[syn64878829]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_689076/ISPY2_689076_0000.nii.gz

Downloading files: 100%|█████████▉| 1.79G/1.79G [05:57<00:00, 5.01MB/s]

[syn64877935]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_689188/ISPY2_689188_0000.nii.gz

Downloading files: 100%|█████████▉| 1.79G/1.79G [05:57<00:00, 5.01MB/s]

[syn64878536]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_689452/ISPY2_689452_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.80G/1.80G [05:59<00:00, 5.02MB/s]

[syn64882252]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_689480/ISPY2_689480_0000.nii.gz

Downloading files: 100%|█████████▉| 1.81G/1.81G [06:00<00:00, 5.02MB/s]

[syn64876038]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_690089/ISPY2_690089_0000.nii.gz

Downloading files: 100%|█████████▉| 1.81G/1.81G [06:00<00:00, 5.02MB/s]

[syn64883546]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_690410/ISPY2_690410_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.81G/1.81G [06:00<00:00, 5.01MB/s]

[syn64872798]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_691753/ISPY2_691753_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.81G/1.81G [06:00<00:00, 5.01MB/s]

[syn64879791]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_692885/ISPY2_692885_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.81G/1.81G [06:01<00:00, 5.01MB/s]

[syn64872979]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_695521/ISPY2_695521_0000.nii.gz

Downloading files: 100%|█████████▉| 1.82G/1.82G [06:02<00:00, 5.01MB/s]

[syn64872275]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_697098/ISPY2_697098_0000.nii.gz

Downloading files: 100%|█████████▉| 1.83G/1.83G [06:03<00:00, 5.02MB/s]

[syn64878312]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_697871/ISPY2_697871_0000.nii.gz

Downloading files: 100%|█████████▉| 1.83G/1.83G [06:04<00:00, 5.02MB/s]

[syn64882027]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_698094/ISPY2_698094_0000.nii.gz

Downloading files: 100%|█████████▉| 1.83G/1.83G [06:05<00:00, 5.02MB/s]

[syn64883219]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_700549/ISPY2_700549_0000.nii.gz

Downloading files: 100%|█████████▉| 1.84G/1.84G [06:06<00:00, 5.03MB/s]

[syn64881907]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_701790/ISPY2_701790_0000.nii.gz

Downloading files: 100%|█████████▉| 1.84G/1.84G [06:06<00:00, 5.03MB/s]

[syn64882441]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_703401/ISPY2_703401_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.84G/1.84G [06:07<00:00, 5.02MB/s]

[syn64883862]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_703455/ISPY2_703455_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.85G/1.85G [06:08<00:00, 5.03MB/s]

[syn64883099]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_705381/ISPY2_705381_0000.nii.gz

Downloading files: 100%|█████████▉| 1.85G/1.85G [06:08<00:00, 5.03MB/s]

[syn64880302]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_706169/ISPY2_706169_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.86G/1.86G [06:09<00:00, 5.03MB/s]

[syn64879546]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_706418/ISPY2_706418_0000.nii.gz

Downloading files: 100%|█████████▉| 1.86G/1.86G [06:10<00:00, 5.03MB/s]

[syn64871337]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_706639/ISPY2_706639_0000.nii.gz

Downloading files: 100%|█████████▉| 1.86G/1.86G [06:10<00:00, 5.02MB/s]

[syn64878900]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_706943/ISPY2_706943_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.86G/1.86G [06:10<00:00, 5.02MB/s]

[syn64882576]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_708387/ISPY2_708387_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.86G/1.86G [06:11<00:00, 5.02MB/s]

[syn64878750]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_709559/ISPY2_709559_0000.nii.gz

Downloading files: 100%|█████████▉| 1.87G/1.87G [06:12<00:00, 5.02MB/s]

[syn64874246]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_711476/ISPY2_711476_0000.nii.gz

Downloading files: 100%|█████████▉| 1.87G/1.87G [06:12<00:00, 5.01MB/s]

[syn64881837]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_712276/ISPY2_712276_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.87G/1.87G [06:13<00:00, 5.01MB/s]

[syn64882081]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_712785/ISPY2_712785_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.87G/1.87G [06:13<00:00, 5.01MB/s]

[syn64877041]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_712917/ISPY2_712917_0000.nii.gz

Downloading files: 100%|█████████▉| 1.87G/1.87G [06:14<00:00, 5.01MB/s]

[syn64881159]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_714205/ISPY2_714205_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.87G/1.87G [06:14<00:00, 5.00MB/s]

[syn64880608]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_719713/ISPY2_719713_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.87G/1.87G [06:14<00:00, 5.00MB/s]

[syn64873810]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_720065/ISPY2_720065_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.88G/1.88G [06:16<00:00, 5.01MB/s]

[syn64883402]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_721099/ISPY2_721099_0000.nii.gz

Downloading files: 100%|█████████▉| 1.89G/1.89G [06:17<00:00, 5.02MB/s]

[syn64876628]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_723918/ISPY2_723918_0000.nii.gz

Downloading files: 100%|█████████▉| 1.90G/1.90G [06:18<00:00, 5.03MB/s]

[syn64880804]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_724293/ISPY2_724293_0000.nii.gz

Downloading files: 100%|█████████▉| 1.90G/1.90G [06:18<00:00, 5.03MB/s]

[syn64872024]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_724384/ISPY2_724384_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.90G/1.90G [06:18<00:00, 5.02MB/s]

[syn64877536]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_725455/ISPY2_725455_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.90G/1.90G [06:19<00:00, 5.02MB/s]

[syn64875530]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_726091/ISPY2_726091_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.91G/1.91G [06:20<00:00, 5.02MB/s]

[syn64882586]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_726381/ISPY2_726381_0000.nii.gz

Downloading files: 100%|█████████▉| 1.91G/1.91G [06:21<00:00, 5.02MB/s]

[syn64883195]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_726940/ISPY2_726940_0000.nii.gz

Downloading files: 100%|█████████▉| 1.91G/1.91G [06:21<00:00, 5.02MB/s]

[syn64875079]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_727255/ISPY2_727255_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.91G/1.91G [06:21<00:00, 5.01MB/s]

[syn64879453]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_727804/ISPY2_727804_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.92G/1.92G [06:22<00:00, 5.02MB/s]

[syn64872787]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_728149/ISPY2_728149_0000.nii.gz

Downloading files: 100%|█████████▉| 1.92G/1.92G [06:23<00:00, 5.02MB/s]

[syn64881552]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_728182/ISPY2_728182_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.94G/1.94G [06:24<00:00, 5.04MB/s]

[syn64875773]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_728287/ISPY2_728287_0000.nii.gz

Downloading files: 100%|█████████▉| 1.94G/1.94G [06:24<00:00, 5.04MB/s]

[syn64880190]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_728714/ISPY2_728714_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.96G/1.96G [06:26<00:00, 5.07MB/s]

[syn64876255]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_729270/ISPY2_729270_0000.nii.gz

Downloading files: 100%|█████████▉| 1.96G/1.96G [06:26<00:00, 5.06MB/s]

[syn64876608]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_729732/ISPY2_729732_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.97G/1.97G [06:27<00:00, 5.08MB/s]

[syn64881361]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_732137/ISPY2_732137_0000.nii.gz

Downloading files: 100%|█████████▉| 1.97G/1.97G [06:27<00:00, 5.08MB/s]

[syn64881486]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_733276/ISPY2_733276_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.98G/1.98G [06:28<00:00, 5.08MB/s]

[syn64879114]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_734997/ISPY2_734997_0000.nii.gz

Downloading files: 100%|█████████▉| 1.98G/1.98G [06:29<00:00, 5.08MB/s]

[syn64872231]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_735673/ISPY2_735673_0000.nii.gz

Downloading files: 100%|█████████▉| 1.98G/1.98G [06:29<00:00, 5.08MB/s]

[syn64872920]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_736721/ISPY2_736721_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.99G/1.99G [06:30<00:00, 5.08MB/s]

[syn64872336]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_738041/ISPY2_738041_0000.nii.gz

Downloading files: 100%|█████████▉| 1.99G/1.99G [06:31<00:00, 5.08MB/s]

[syn64877076]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_741535/ISPY2_741535_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 1.99G/1.99G [06:32<00:00, 5.07MB/s]

[syn64873293]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_742477/ISPY2_742477_0000.nii.gz

Downloading files: 100%|█████████▉| 1.99G/1.99G [06:33<00:00, 5.07MB/s]

[syn64873947]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_745633/ISPY2_745633_0000.nii.gz

Downloading files: 100%|█████████▉| 2.00G/2.00G [06:33<00:00, 5.07MB/s]

[syn64878571]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_746265/ISPY2_746265_0000.nii.gz

Downloading files: 100%|█████████▉| 2.00G/2.00G [06:34<00:00, 5.07MB/s]

[syn64882502]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_746731/ISPY2_746731_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.00G/2.00G [06:34<00:00, 5.07MB/s]

[syn64877910]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_748583/ISPY2_748583_0000.nii.gz

Downloading files: 100%|█████████▉| 2.00G/2.00G [06:35<00:00, 5.07MB/s]

[syn64877548]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_748611/ISPY2_748611_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.01G/2.01G [06:36<00:00, 5.07MB/s]

[syn64872697]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_749097/ISPY2_749097_0000.nii.gz

Downloading files: 100%|█████████▉| 2.02G/2.02G [06:37<00:00, 5.09MB/s]

[syn64876826]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_752372/ISPY2_752372_0000.nii.gz

Downloading files: 100%|█████████▉| 2.04G/2.04G [06:39<00:00, 5.10MB/s]

[syn64880413]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_752469/ISPY2_752469_0000.nii.gz

Downloading files: 100%|█████████▉| 2.04G/2.04G [06:39<00:00, 5.10MB/s]

[syn64882233]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_753109/ISPY2_753109_0000.nii.gz

Downloading files: 100%|█████████▉| 2.05G/2.05G [06:40<00:00, 5.11MB/s]

[syn64883846]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_755914/ISPY2_755914_0000.nii.gz

Downloading files: 100%|█████████▉| 2.05G/2.05G [06:41<00:00, 5.10MB/s]

[syn64873380]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_756412/ISPY2_756412_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.05G/2.05G [06:41<00:00, 5.10MB/s]

[syn64881086]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_759015/ISPY2_759015_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.05G/2.05G [06:42<00:00, 5.10MB/s]

[syn64880849]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_759418/ISPY2_759418_0000.nii.gz

Downloading files: 100%|█████████▉| 2.05G/2.05G [06:42<00:00, 5.10MB/s]

[syn64882485]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_760011/ISPY2_760011_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.06G/2.06G [06:43<00:00, 5.10MB/s]

[syn64874441]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_760901/ISPY2_760901_0000.nii.gz

Downloading files: 100%|█████████▉| 2.06G/2.06G [06:44<00:00, 5.10MB/s]

[syn64882121]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_765671/ISPY2_765671_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.06G/2.06G [06:44<00:00, 5.10MB/s]

[syn64879228]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_765773/ISPY2_765773_0000.nii.gz

Downloading files: 100%|█████████▉| 2.06G/2.06G [06:45<00:00, 5.10MB/s]

[syn64877136]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_766301/ISPY2_766301_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.06G/2.06G [06:45<00:00, 5.09MB/s]

[syn64883078]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_766967/ISPY2_766967_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.06G/2.06G [06:45<00:00, 5.09MB/s]

[syn64881214]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_767081/ISPY2_767081_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.07G/2.07G [06:46<00:00, 5.10MB/s]

[syn64882544]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_767934/ISPY2_767934_0000.nii.gz

Downloading files: 100%|█████████▉| 2.09G/2.09G [06:48<00:00, 5.13MB/s]

[syn64871967]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_768214/ISPY2_768214_0000.nii.gz

Downloading files: 100%|█████████▉| 2.09G/2.09G [06:48<00:00, 5.12MB/s]

[syn64881769]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_769972/ISPY2_769972_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.09G/2.09G [06:48<00:00, 5.12MB/s]

[syn64874003]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_771151/ISPY2_771151_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.09G/2.09G [06:49<00:00, 5.12MB/s]

[syn64882492]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_771443/ISPY2_771443_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.09G/2.09G [06:49<00:00, 5.11MB/s]

[syn64877857]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_771813/ISPY2_771813_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.10G/2.10G [06:50<00:00, 5.11MB/s]

[syn64881708]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_774840/ISPY2_774840_0000.nii.gz

Downloading files: 100%|█████████▉| 2.10G/2.10G [06:50<00:00, 5.11MB/s]

[syn64880276]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_775346/ISPY2_775346_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.10G/2.10G [06:50<00:00, 5.11MB/s]

[syn64874720]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_778020/ISPY2_778020_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.11G/2.11G [06:52<00:00, 5.13MB/s]

[syn64878504]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_778527/ISPY2_778527_0000.nii.gz

Downloading files: 100%|█████████▉| 2.11G/2.11G [06:52<00:00, 5.12MB/s]

[syn64880436]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_779739/ISPY2_779739_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.11G/2.11G [06:52<00:00, 5.12MB/s]

[syn64873018]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_780272/ISPY2_780272_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.12G/2.12G [06:53<00:00, 5.13MB/s]

[syn64880343]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_781335/ISPY2_781335_0000.nii.gz

Downloading files: 100%|█████████▉| 2.13G/2.13G [06:54<00:00, 5.14MB/s]

[syn64883420]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_781642/ISPY2_781642_0000.nii.gz

Downloading files: 100%|█████████▉| 2.13G/2.13G [06:55<00:00, 5.14MB/s]

[syn64880551]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_782334/ISPY2_782334_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.13G/2.13G [06:55<00:00, 5.13MB/s]

[syn64882157]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_783427/ISPY2_783427_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.13G/2.13G [06:55<00:00, 5.13MB/s]

[syn64881655]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_783578/ISPY2_783578_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.13G/2.13G [06:56<00:00, 5.12MB/s]

[syn64877830]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_783764/ISPY2_783764_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.13G/2.13G [06:56<00:00, 5.12MB/s]

[syn64879845]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_783771/ISPY2_783771_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.13G/2.13G [06:56<00:00, 5.12MB/s]

[syn64878483]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_786003/ISPY2_786003_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.13G/2.13G [06:57<00:00, 5.11MB/s]

[syn64878379]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_786480/ISPY2_786480_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.14G/2.14G [06:58<00:00, 5.12MB/s]

[syn64879995]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_786753/ISPY2_786753_0000.nii.gz

Downloading files: 100%|█████████▉| 2.16G/2.16G [06:59<00:00, 5.15MB/s]

[syn64882693]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_787415/ISPY2_787415_0000.nii.gz

Downloading files: 100%|█████████▉| 2.17G/2.17G [07:01<00:00, 5.16MB/s]

[syn64872384]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_788149/ISPY2_788149_0000.nii.gz

Downloading files: 100%|█████████▉| 2.17G/2.17G [07:01<00:00, 5.15MB/s]

[syn64874814]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_789497/ISPY2_789497_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.17G/2.17G [07:01<00:00, 5.15MB/s]

[syn64880261]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_790070/ISPY2_790070_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.18G/2.18G [07:02<00:00, 5.15MB/s]

[syn64881275]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_790397/ISPY2_790397_0000.nii.gz

Downloading files: 100%|█████████▉| 2.18G/2.18G [07:03<00:00, 5.14MB/s]

[syn64876803]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_790722/ISPY2_790722_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.18G/2.18G [07:03<00:00, 5.14MB/s]

[syn64880176]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_791321/ISPY2_791321_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.20G/2.20G [07:04<00:00, 5.17MB/s]

[syn64882203]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_791944/ISPY2_791944_0000.nii.gz

Downloading files: 100%|█████████▉| 2.20G/2.20G [07:05<00:00, 5.17MB/s]

[syn64880151]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_792181/ISPY2_792181_0000.nii.gz

Downloading files: 100%|█████████▉| 2.20G/2.20G [07:05<00:00, 5.17MB/s]

[syn64881879]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_792412/ISPY2_792412_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.21G/2.21G [07:07<00:00, 5.18MB/s]

[syn64883907]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_793155/ISPY2_793155_0000.nii.gz

Downloading files: 100%|█████████▉| 2.22G/2.22G [07:08<00:00, 5.18MB/s]

[syn64877742]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_793684/ISPY2_793684_0000.nii.gz

Downloading files: 100%|█████████▉| 2.22G/2.22G [07:09<00:00, 5.19MB/s]

[syn64879725]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_794128/ISPY2_794128_0000.nii.gz

Downloading files: 100%|█████████▉| 2.23G/2.23G [07:09<00:00, 5.19MB/s]

[syn64876817]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_794428/ISPY2_794428_0000.nii.gz

Downloading files: 100%|█████████▉| 2.24G/2.24G [07:10<00:00, 5.20MB/s]

[syn64875671]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_795996/ISPY2_795996_0000.nii.gz

Downloading files: 100%|█████████▉| 2.24G/2.24G [07:11<00:00, 5.20MB/s]

[syn64872840]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_796558/ISPY2_796558_0000.nii.gz

Downloading files: 100%|█████████▉| 2.24G/2.24G [07:12<00:00, 5.19MB/s]

[syn64880015]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_797427/ISPY2_797427_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.25G/2.25G [07:12<00:00, 5.19MB/s]

[syn64883821]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_797499/ISPY2_797499_0000.nii.gz

Downloading files: 100%|█████████▉| 2.25G/2.25G [07:13<00:00, 5.19MB/s]

[syn64879315]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_797639/ISPY2_797639_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.27G/2.27G [07:14<00:00, 5.22MB/s]

[syn64876997]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_798604/ISPY2_798604_0000.nii.gz

Downloading files: 100%|█████████▉| 2.27G/2.27G [07:14<00:00, 5.22MB/s]

[syn64881224]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_799149/ISPY2_799149_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.28G/2.28G [07:16<00:00, 5.22MB/s]

[syn64873632]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_800447/ISPY2_800447_0000.nii.gz

Downloading files: 100%|█████████▉| 2.28G/2.28G [07:17<00:00, 5.22MB/s]

[syn64881926]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_800710/ISPY2_800710_0000.nii.gz

Downloading files: 100%|█████████▉| 2.29G/2.29G [07:18<00:00, 5.23MB/s]

[syn64872414]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_801641/ISPY2_801641_0000.nii.gz

Downloading files: 100%|█████████▉| 2.29G/2.29G [07:19<00:00, 5.22MB/s]

[syn64879142]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_802105/ISPY2_802105_0000.nii.gz

Downloading files: 100%|█████████▉| 2.30G/2.30G [07:20<00:00, 5.22MB/s]

[syn64881201]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_802308/ISPY2_802308_0000.nii.gz

Downloading files: 100%|█████████▉| 2.30G/2.30G [07:20<00:00, 5.22MB/s]

[syn64874029]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_802778/ISPY2_802778_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.31G/2.31G [07:21<00:00, 5.22MB/s]

[syn64876522]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_803514/ISPY2_803514_0000.nii.gz

Downloading files: 100%|█████████▉| 2.32G/2.32G [07:22<00:00, 5.23MB/s]

[syn64871260]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_803677/ISPY2_803677_0000.nii.gz

Downloading files: 100%|█████████▉| 2.32G/2.32G [07:23<00:00, 5.23MB/s]

[syn64873603]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_804233/ISPY2_804233_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.32G/2.32G [07:24<00:00, 5.23MB/s]

[syn64881320]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_804979/ISPY2_804979_0000.nii.gz

Downloading files: 100%|█████████▉| 2.32G/2.32G [07:24<00:00, 5.23MB/s]

[syn64873115]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_805136/ISPY2_805136_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.34G/2.34G [07:25<00:00, 5.24MB/s]

[syn64881464]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_808714/ISPY2_808714_0000.nii.gz

Downloading files: 100%|█████████▉| 2.34G/2.34G [07:26<00:00, 5.24MB/s]

[syn64877031]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_809037/ISPY2_809037_0000.nii.gz

Downloading files: 100%|█████████▉| 2.34G/2.34G [07:27<00:00, 5.23MB/s]

[syn64881357]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_809649/ISPY2_809649_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.34G/2.34G [07:28<00:00, 5.23MB/s]

[syn64881138]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_810965/ISPY2_810965_0000.nii.gz

Downloading files: 100%|█████████▉| 2.34G/2.34G [07:28<00:00, 5.23MB/s]

[syn64874409]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_812089/ISPY2_812089_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.34G/2.34G [07:28<00:00, 5.22MB/s]

[syn64873510]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_814299/ISPY2_814299_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.35G/2.35G [07:29<00:00, 5.22MB/s]

[syn64872484]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_815421/ISPY2_815421_0000.nii.gz

Downloading files: 100%|█████████▉| 2.35G/2.35G [07:30<00:00, 5.22MB/s]

[syn64882919]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_815493/ISPY2_815493_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.35G/2.35G [07:30<00:00, 5.21MB/s]

[syn64880722]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_819622/ISPY2_819622_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.35G/2.35G [07:30<00:00, 5.21MB/s]

[syn64873170]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_820348/ISPY2_820348_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.35G/2.35G [07:31<00:00, 5.21MB/s]

[syn64877340]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_820807/ISPY2_820807_0000.nii.gz

Downloading files: 100%|█████████▉| 2.36G/2.36G [07:32<00:00, 5.22MB/s]

[syn64877303]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_823618/ISPY2_823618_0000.nii.gz

Downloading files: 100%|█████████▉| 2.36G/2.36G [07:32<00:00, 5.21MB/s]

[syn64879948]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_824234/ISPY2_824234_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.36G/2.36G [07:33<00:00, 5.21MB/s]

[syn64879293]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_824350/ISPY2_824350_0000.nii.gz

Downloading files: 100%|█████████▉| 2.36G/2.36G [07:33<00:00, 5.21MB/s]

[syn64872990]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_824512/ISPY2_824512_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.36G/2.36G [07:34<00:00, 5.21MB/s]

[syn64875806]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_825363/ISPY2_825363_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.36G/2.36G [07:34<00:00, 5.20MB/s]

[syn64881265]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_828199/ISPY2_828199_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.36G/2.36G [07:34<00:00, 5.20MB/s]

[syn64878386]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_829491/ISPY2_829491_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.37G/2.37G [07:35<00:00, 5.20MB/s]

[syn64871218]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_830486/ISPY2_830486_0000.nii.gz

Downloading files: 100%|█████████▉| 2.37G/2.37G [07:36<00:00, 5.20MB/s]

[syn64871497]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_830958/ISPY2_830958_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.38G/2.38G [07:37<00:00, 5.20MB/s]

[syn64883141]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_831702/ISPY2_831702_0000.nii.gz

Downloading files: 100%|█████████▉| 2.38G/2.38G [07:37<00:00, 5.20MB/s]

[syn64878018]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_831848/ISPY2_831848_0000.nii.gz

Downloading files: 100%|█████████▉| 2.39G/2.39G [07:39<00:00, 5.21MB/s]

[syn64879122]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_832056/ISPY2_832056_0000.nii.gz

Downloading files: 100%|█████████▉| 2.40G/2.40G [07:40<00:00, 5.22MB/s]

[syn64877267]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_833536/ISPY2_833536_0000.nii.gz

Downloading files: 100%|█████████▉| 2.40G/2.40G [07:40<00:00, 5.22MB/s]

[syn64883468]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_834418/ISPY2_834418_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.41G/2.41G [07:41<00:00, 5.21MB/s]

[syn64880407]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_835658/ISPY2_835658_0000.nii.gz

Downloading files: 100%|█████████▉| 2.41G/2.41G [07:42<00:00, 5.21MB/s]

[syn64882973]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_836114/ISPY2_836114_0000.nii.gz

Downloading files: 100%|█████████▉| 2.43G/2.43G [07:43<00:00, 5.23MB/s]

[syn64879405]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_836983/ISPY2_836983_0000.nii.gz

Downloading files: 100%|█████████▉| 2.43G/2.43G [07:44<00:00, 5.24MB/s]

[syn64874152]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_839274/ISPY2_839274_0000.nii.gz

Downloading files: 100%|█████████▉| 2.43G/2.43G [07:45<00:00, 5.23MB/s]

[syn64883702]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_840501/ISPY2_840501_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.44G/2.44G [07:45<00:00, 5.23MB/s]

[syn64872137]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_841336/ISPY2_841336_0000.nii.gz

Downloading files: 100%|█████████▉| 2.44G/2.44G [07:46<00:00, 5.23MB/s]

[syn64877350]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_843554/ISPY2_843554_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.44G/2.44G [07:47<00:00, 5.22MB/s]

[syn64880115]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_845079/ISPY2_845079_0000.nii.gz

Downloading files: 100%|█████████▉| 2.45G/2.45G [07:48<00:00, 5.23MB/s]

[syn64871767]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_845147/ISPY2_845147_0000.nii.gz

Downloading files: 100%|█████████▉| 2.45G/2.45G [07:49<00:00, 5.22MB/s]

[syn64873186]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_845663/ISPY2_845663_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.45G/2.45G [07:49<00:00, 5.22MB/s]

[syn64882751]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_845783/ISPY2_845783_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.47G/2.47G [07:50<00:00, 5.25MB/s]

[syn64877461]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_846156/ISPY2_846156_0000.nii.gz

Downloading files: 100%|█████████▉| 2.48G/2.48G [07:51<00:00, 5.25MB/s]

[syn64871452]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_847272/ISPY2_847272_0000.nii.gz

Downloading files: 100%|█████████▉| 2.48G/2.48G [07:52<00:00, 5.25MB/s]

[syn64882138]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_847753/ISPY2_847753_0000.nii.gz

Downloading files: 100%|█████████▉| 2.48G/2.48G [07:53<00:00, 5.24MB/s]

[syn64880391]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_848003/ISPY2_848003_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.48G/2.48G [07:53<00:00, 5.24MB/s]

[syn64879602]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_848371/ISPY2_848371_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.49G/2.49G [07:54<00:00, 5.24MB/s]

[syn64883571]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_849605/ISPY2_849605_0000.nii.gz

Downloading files: 100%|█████████▉| 2.49G/2.49G [07:55<00:00, 5.24MB/s]

[syn64876361]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_851180/ISPY2_851180_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.49G/2.49G [07:55<00:00, 5.24MB/s]

[syn64872365]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_851223/ISPY2_851223_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.49G/2.49G [07:55<00:00, 5.23MB/s]

[syn64871822]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_851488/ISPY2_851488_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.50G/2.50G [07:56<00:00, 5.23MB/s]

[syn64883181]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_856159/ISPY2_856159_0000.nii.gz

Downloading files: 100%|█████████▉| 2.50G/2.50G [07:57<00:00, 5.23MB/s]

[syn64880037]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_857165/ISPY2_857165_0000.nii.gz

Downloading files: 100%|█████████▉| 2.52G/2.52G [07:58<00:00, 5.25MB/s]

[syn64879939]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_859699/ISPY2_859699_0000.nii.gz

Downloading files: 100%|█████████▉| 2.52G/2.52G [07:59<00:00, 5.25MB/s]

[syn64877390]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_860243/ISPY2_860243_0000.nii.gz

Downloading files: 100%|█████████▉| 2.52G/2.52G [08:00<00:00, 5.25MB/s]

[syn64883160]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_860901/ISPY2_860901_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.52G/2.52G [08:00<00:00, 5.24MB/s]

[syn64879216]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_861745/ISPY2_861745_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.53G/2.53G [08:01<00:00, 5.25MB/s]

[syn64879012]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_862244/ISPY2_862244_0000.nii.gz

Downloading files: 100%|█████████▉| 2.55G/2.55G [08:03<00:00, 5.27MB/s]

[syn64882982]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_863161/ISPY2_863161_0000.nii.gz

Downloading files: 100%|█████████▉| 2.57G/2.57G [08:04<00:00, 5.30MB/s]

[syn64873330]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_865416/ISPY2_865416_0000.nii.gz

Downloading files: 100%|█████████▉| 2.57G/2.57G [08:05<00:00, 5.30MB/s]

[syn64876922]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_866660/ISPY2_866660_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.57G/2.57G [08:05<00:00, 5.29MB/s]

[syn64878757]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_870077/ISPY2_870077_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.57G/2.57G [08:06<00:00, 5.29MB/s]

[syn64879396]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_872188/ISPY2_872188_0000.nii.gz

Downloading files: 100%|█████████▉| 2.59G/2.59G [08:07<00:00, 5.30MB/s]

[syn64881151]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_873686/ISPY2_873686_0000.nii.gz

Downloading files: 100%|█████████▉| 2.59G/2.59G [08:08<00:00, 5.30MB/s]

[syn64883278]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_875089/ISPY2_875089_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.59G/2.59G [08:08<00:00, 5.30MB/s]

[syn64877283]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_876511/ISPY2_876511_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.61G/2.61G [08:09<00:00, 5.32MB/s]

[syn64874044]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_877463/ISPY2_877463_0000.nii.gz

Downloading files: 100%|█████████▉| 2.61G/2.61G [08:10<00:00, 5.32MB/s]

[syn64879077]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_879224/ISPY2_879224_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.61G/2.61G [08:10<00:00, 5.31MB/s]

[syn64871183]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_882538/ISPY2_882538_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.61G/2.61G [08:10<00:00, 5.31MB/s]

[syn64874120]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_882553/ISPY2_882553_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.61G/2.61G [08:11<00:00, 5.31MB/s]

[syn64876023]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_883696/ISPY2_883696_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.62G/2.62G [08:12<00:00, 5.32MB/s]

[syn64883184]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_883886/ISPY2_883886_0000.nii.gz

Downloading files: 100%|█████████▉| 2.63G/2.63G [08:13<00:00, 5.32MB/s]

[syn64880884]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_884011/ISPY2_884011_0000.nii.gz

Downloading files: 100%|█████████▉| 2.63G/2.63G [08:14<00:00, 5.32MB/s]

[syn64882635]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_884266/ISPY2_884266_0000.nii.gz

Downloading files: 100%|█████████▉| 2.64G/2.64G [08:15<00:00, 5.32MB/s]

[syn64880198]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_885590/ISPY2_885590_0000.nii.gz

Downloading files: 100%|█████████▉| 2.64G/2.64G [08:16<00:00, 5.32MB/s]

[syn64882320]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_885871/ISPY2_885871_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.64G/2.64G [08:16<00:00, 5.32MB/s]

[syn64878807]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_887594/ISPY2_887594_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.64G/2.64G [08:16<00:00, 5.31MB/s]

[syn64882682]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_889049/ISPY2_889049_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.64G/2.64G [08:17<00:00, 5.31MB/s]

[syn64872668]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_889225/ISPY2_889225_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.64G/2.64G [08:17<00:00, 5.31MB/s]

[syn64881430]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_889721/ISPY2_889721_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.64G/2.64G [08:18<00:00, 5.31MB/s]

[syn64877758]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_890372/ISPY2_890372_0000.nii.gz

Downloading files: 100%|█████████▉| 2.64G/2.64G [08:18<00:00, 5.30MB/s]

[syn64873908]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_890414/ISPY2_890414_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.64G/2.64G [08:19<00:00, 5.30MB/s]

[syn64882022]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_891645/ISPY2_891645_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.66G/2.66G [08:20<00:00, 5.31MB/s]

[syn64874584]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_892390/ISPY2_892390_0000.nii.gz

Downloading files: 100%|█████████▉| 2.66G/2.66G [08:21<00:00, 5.31MB/s]

[syn64880206]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_893874/ISPY2_893874_0000.nii.gz

Downloading files: 100%|█████████▉| 2.67G/2.67G [08:22<00:00, 5.31MB/s]

[syn64876693]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_894128/ISPY2_894128_0000.nii.gz

Downloading files: 100%|█████████▉| 2.67G/2.67G [08:22<00:00, 5.31MB/s]

[syn64882495]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_894491/ISPY2_894491_0000.nii.gz

Downloading files: 100%|█████████▉| 2.69G/2.69G [08:24<00:00, 5.34MB/s]

[syn64878462]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_894673/ISPY2_894673_0000.nii.gz

Downloading files: 100%|█████████▉| 2.70G/2.70G [08:25<00:00, 5.34MB/s]

[syn64876946]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_895653/ISPY2_895653_0000.nii.gz

Downloading files: 100%|█████████▉| 2.72G/2.72G [08:26<00:00, 5.36MB/s]

[syn64878992]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_896621/ISPY2_896621_0000.nii.gz

Downloading files: 100%|█████████▉| 2.73G/2.73G [08:27<00:00, 5.37MB/s]

[syn64875709]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_896852/ISPY2_896852_0000.nii.gz

Downloading files: 100%|█████████▉| 2.73G/2.73G [08:28<00:00, 5.36MB/s]

[syn64879953]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_896939/ISPY2_896939_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.73G/2.73G [08:28<00:00, 5.36MB/s]

[syn64880257]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_898618/ISPY2_898618_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.73G/2.73G [08:28<00:00, 5.36MB/s]

[syn64878940]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_899381/ISPY2_899381_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.73G/2.73G [08:29<00:00, 5.36MB/s]

[syn64882477]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_899692/ISPY2_899692_0000.nii.gz

Downloading files: 100%|█████████▉| 2.74G/2.74G [08:30<00:00, 5.37MB/s]

[syn64880488]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_900959/ISPY2_900959_0000.nii.gz

Downloading files: 100%|█████████▉| 2.74G/2.74G [08:30<00:00, 5.36MB/s]

[syn64882609]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_901705/ISPY2_901705_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.74G/2.74G [08:31<00:00, 5.36MB/s]

[syn64881680]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_903880/ISPY2_903880_0000.nii.gz

Downloading files: 100%|█████████▉| 2.74G/2.74G [08:31<00:00, 5.36MB/s]

[syn64883707]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_904269/ISPY2_904269_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.75G/2.75G [08:32<00:00, 5.36MB/s]

[syn64882664]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_905264/ISPY2_905264_0000.nii.gz

Downloading files: 100%|█████████▉| 2.75G/2.75G [08:33<00:00, 5.36MB/s]

[syn64881081]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_906042/ISPY2_906042_0000.nii.gz

Downloading files: 100%|█████████▉| 2.76G/2.76G [08:34<00:00, 5.36MB/s]

[syn64877572]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_906795/ISPY2_906795_0000.nii.gz

Downloading files: 100%|█████████▉| 2.76G/2.76G [08:34<00:00, 5.36MB/s]

[syn64877247]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_910188/ISPY2_910188_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.76G/2.76G [08:34<00:00, 5.36MB/s]

[syn64883805]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_910706/ISPY2_910706_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.76G/2.76G [08:35<00:00, 5.35MB/s]

[syn64878326]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_912836/ISPY2_912836_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.76G/2.76G [08:36<00:00, 5.35MB/s]

[syn64879718]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_913225/ISPY2_913225_0000.nii.gz

Downloading files: 100%|█████████▉| 2.77G/2.77G [08:36<00:00, 5.35MB/s]

[syn64877013]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_913527/ISPY2_913527_0000.nii.gz

Downloading files: 100%|█████████▉| 2.77G/2.77G [08:37<00:00, 5.36MB/s]

[syn64882871]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_914968/ISPY2_914968_0000.nii.gz

Downloading files: 100%|█████████▉| 2.77G/2.77G [08:38<00:00, 5.35MB/s]

[syn64876403]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_916586/ISPY2_916586_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.77G/2.77G [08:38<00:00, 5.35MB/s]

[syn64880166]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_916645/ISPY2_916645_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.77G/2.77G [08:38<00:00, 5.35MB/s]

[syn64873871]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_917762/ISPY2_917762_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.78G/2.78G [08:39<00:00, 5.35MB/s]

[syn64878951]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_918979/ISPY2_918979_0000.nii.gz

Downloading files: 100%|█████████▉| 2.78G/2.78G [08:40<00:00, 5.35MB/s]

[syn64882698]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_920479/ISPY2_920479_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.78G/2.78G [08:40<00:00, 5.35MB/s]

[syn64880733]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_922872/ISPY2_922872_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.80G/2.80G [08:41<00:00, 5.37MB/s]

[syn64874610]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_923968/ISPY2_923968_0000.nii.gz

Downloading files: 100%|█████████▉| 2.80G/2.80G [08:41<00:00, 5.37MB/s]

[syn64878582]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_924071/ISPY2_924071_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.80G/2.80G [08:42<00:00, 5.36MB/s]

[syn64880670]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_924812/ISPY2_924812_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.80G/2.80G [08:42<00:00, 5.36MB/s]

[syn64878231]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_924868/ISPY2_924868_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.80G/2.80G [08:42<00:00, 5.36MB/s]

[syn64882424]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_924895/ISPY2_924895_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.80G/2.80G [08:43<00:00, 5.36MB/s]

[syn64883484]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_925691/ISPY2_925691_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.81G/2.81G [08:44<00:00, 5.36MB/s]

[syn64878857]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_928170/ISPY2_928170_0000.nii.gz

Downloading files: 100%|█████████▉| 2.82G/2.82G [08:45<00:00, 5.37MB/s]

[syn64882948]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_928446/ISPY2_928446_0000.nii.gz

Downloading files: 100%|█████████▉| 2.82G/2.82G [08:46<00:00, 5.37MB/s]

[syn64883676]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_928815/ISPY2_928815_0000.nii.gz

Downloading files: 100%|█████████▉| 2.83G/2.83G [08:47<00:00, 5.36MB/s]

[syn64879618]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_929391/ISPY2_929391_0000.nii.gz

Downloading files: 100%|█████████▉| 2.83G/2.83G [08:47<00:00, 5.37MB/s]

[syn64880768]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_929980/ISPY2_929980_0000.nii.gz

Downloading files: 100%|█████████▉| 2.84G/2.84G [08:48<00:00, 5.37MB/s]

[syn64871921]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_930172/ISPY2_930172_0000.nii.gz

Downloading files: 100%|█████████▉| 2.84G/2.84G [08:48<00:00, 5.37MB/s]

[syn64878024]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_930853/ISPY2_930853_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.84G/2.84G [08:49<00:00, 5.37MB/s]

[syn64871354]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_930903/ISPY2_930903_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.84G/2.84G [08:49<00:00, 5.37MB/s]

[syn64875409]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_932200/ISPY2_932200_0000.nii.gz

Downloading files: 100%|█████████▉| 2.84G/2.84G [08:50<00:00, 5.37MB/s]

[syn64881663]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_934459/ISPY2_934459_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.84G/2.84G [08:50<00:00, 5.36MB/s]

[syn64877188]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_934906/ISPY2_934906_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.84G/2.84G [08:50<00:00, 5.36MB/s]

[syn64879417]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_935460/ISPY2_935460_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.85G/2.85G [08:51<00:00, 5.36MB/s]

[syn64879179]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_938719/ISPY2_938719_0000.nii.gz

Downloading files: 100%|█████████▉| 2.85G/2.85G [08:52<00:00, 5.36MB/s]

[syn64877802]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_940186/ISPY2_940186_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.85G/2.85G [08:52<00:00, 5.35MB/s]

[syn64879371]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_941191/ISPY2_941191_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.86G/2.86G [08:53<00:00, 5.36MB/s]

[syn64879536]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_941926/ISPY2_941926_0000.nii.gz

Downloading files: 100%|█████████▉| 2.86G/2.86G [08:53<00:00, 5.36MB/s]

[syn64876010]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_942017/ISPY2_942017_0000.nii.gz

Downloading files: 100%|█████████▉| 2.87G/2.87G [08:54<00:00, 5.36MB/s]

[syn64882557]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_943633/ISPY2_943633_0000.nii.gz

Downloading files: 100%|█████████▉| 2.87G/2.87G [08:55<00:00, 5.36MB/s]

[syn64871734]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_943879/ISPY2_943879_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.87G/2.87G [08:55<00:00, 5.35MB/s]

[syn64877556]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_944419/ISPY2_944419_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.87G/2.87G [08:55<00:00, 5.35MB/s]

[syn64881673]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_944536/ISPY2_944536_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.87G/2.87G [08:56<00:00, 5.35MB/s]

[syn64874357]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_946927/ISPY2_946927_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.87G/2.87G [08:56<00:00, 5.34MB/s]

[syn64880894]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_947398/ISPY2_947398_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.87G/2.87G [08:56<00:00, 5.34MB/s]

[syn64871196]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_949444/ISPY2_949444_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.87G/2.87G [08:57<00:00, 5.34MB/s]

[syn64882415]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_950131/ISPY2_950131_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.87G/2.87G [08:57<00:00, 5.33MB/s]

[syn64881522]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_950742/ISPY2_950742_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.88G/2.88G [08:58<00:00, 5.34MB/s]

[syn64882955]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_953262/ISPY2_953262_0000.nii.gz

Downloading files: 100%|█████████▉| 2.89G/2.89G [08:59<00:00, 5.35MB/s]

[syn64881241]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_953885/ISPY2_953885_0000.nii.gz

Downloading files: 100%|█████████▉| 2.89G/2.89G [09:00<00:00, 5.34MB/s]

[syn64879209]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_955035/ISPY2_955035_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.90G/2.90G [09:01<00:00, 5.36MB/s]

[syn64883689]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_955953/ISPY2_955953_0000.nii.gz

Downloading files: 100%|█████████▉| 2.90G/2.90G [09:01<00:00, 5.36MB/s]

[syn64875610]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_957408/ISPY2_957408_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.91G/2.91G [09:02<00:00, 5.36MB/s]

[syn64882054]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_959366/ISPY2_959366_0000.nii.gz

Downloading files: 100%|█████████▉| 2.91G/2.91G [09:03<00:00, 5.36MB/s]

[syn64879710]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_960029/ISPY2_960029_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.93G/2.93G [09:04<00:00, 5.38MB/s]

[syn64883042]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_960490/ISPY2_960490_0000.nii.gz

Downloading files: 100%|█████████▉| 2.93G/2.93G [09:04<00:00, 5.38MB/s]

[syn64880294]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_960963/ISPY2_960963_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.94G/2.94G [09:05<00:00, 5.38MB/s]

[syn64883491]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_962153/ISPY2_962153_0000.nii.gz

Downloading files: 100%|█████████▉| 2.94G/2.94G [09:05<00:00, 5.38MB/s]

[syn64878621]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_962472/ISPY2_962472_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.94G/2.94G [09:06<00:00, 5.38MB/s]

[syn64872532]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_962664/ISPY2_962664_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.95G/2.95G [09:07<00:00, 5.39MB/s]

[syn64882040]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_962827/ISPY2_962827_0000.nii.gz

Downloading files: 100%|█████████▉| 2.95G/2.95G [09:08<00:00, 5.38MB/s]

[syn64882269]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_963303/ISPY2_963303_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.95G/2.95G [09:08<00:00, 5.38MB/s]

[syn64872650]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_963604/ISPY2_963604_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.95G/2.95G [09:09<00:00, 5.38MB/s]

[syn64878450]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_965265/ISPY2_965265_0000.nii.gz

Downloading files: 100%|█████████▉| 2.96G/2.96G [09:09<00:00, 5.38MB/s]

[syn64880628]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_966016/ISPY2_966016_0000.nii.gz

Downloading files: 100%|█████████▉| 2.96G/2.96G [09:10<00:00, 5.38MB/s]

[syn64874089]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_970839/ISPY2_970839_0000.nii.gz

Downloading files: 100%|█████████▉| 2.96G/2.96G [09:10<00:00, 5.37MB/s]

[syn64880082]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_971492/ISPY2_971492_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.96G/2.96G [09:11<00:00, 5.37MB/s]

[syn64871694]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_972307/ISPY2_972307_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.96G/2.96G [09:11<00:00, 5.37MB/s]

[syn64879810]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_973837/ISPY2_973837_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.96G/2.96G [09:11<00:00, 5.37MB/s]

[syn64879496]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_974181/ISPY2_974181_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.96G/2.96G [09:12<00:00, 5.36MB/s]

[syn64875142]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_974618/ISPY2_974618_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.96G/2.96G [09:12<00:00, 5.36MB/s]

[syn64880692]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_981461/ISPY2_981461_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.97G/2.97G [09:13<00:00, 5.36MB/s]

[syn64880443]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_981664/ISPY2_981664_0000.nii.gz

Downloading files: 100%|█████████▉| 2.97G/2.97G [09:14<00:00, 5.37MB/s]

[syn64881888]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_982086/ISPY2_982086_0000.nii.gz

Downloading files: 100%|█████████▉| 2.97G/2.97G [09:14<00:00, 5.36MB/s]

[syn64883334]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_982505/ISPY2_982505_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.97G/2.97G [09:14<00:00, 5.36MB/s]

[syn64878007]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_983841/ISPY2_983841_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.97G/2.97G [09:14<00:00, 5.36MB/s]

[syn64881729]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_986734/ISPY2_986734_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.97G/2.97G [09:15<00:00, 5.35MB/s]

[syn64877329]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_987728/ISPY2_987728_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.97G/2.97G [09:15<00:00, 5.35MB/s]

[syn64876088]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_987914/ISPY2_987914_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.97G/2.97G [09:15<00:00, 5.35MB/s]

[syn64872963]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_987995/ISPY2_987995_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.97G/2.97G [09:16<00:00, 5.35MB/s]

[syn64882166]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_988443/ISPY2_988443_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.97G/2.97G [09:16<00:00, 5.34MB/s]

[syn64876071]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_988665/ISPY2_988665_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.97G/2.97G [09:16<00:00, 5.34MB/s]

[syn64878440]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_990443/ISPY2_990443_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.98G/2.98G [09:18<00:00, 5.34MB/s]

[syn64883666]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_991818/ISPY2_991818_0000.nii.gz

Downloading files: 100%|█████████▉| 2.98G/2.98G [09:18<00:00, 5.34MB/s]

[syn64881366]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_992609/ISPY2_992609_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 2.99G/2.99G [09:19<00:00, 5.34MB/s]

[syn64881789]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_994987/ISPY2_994987_0000.nii.gz

Downloading files: 100%|█████████▉| 2.99G/2.99G [09:20<00:00, 5.34MB/s]

[syn64874515]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_995480/ISPY2_995480_0000.nii.gz

Downloading files: 100%|█████████▉| 3.00G/3.00G [09:21<00:00, 5.34MB/s]

[syn64879224]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_997702/ISPY2_997702_0000.nii.gz

Downloading files: 100%|█████████▉| 3.00G/3.00G [09:22<00:00, 5.34MB/s]

[syn64883083]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_999264/ISPY2_999264_0000.nii.gz

Downloading files: 100%|█████████▉| 3.00G/3.00G [09:22<00:00, 5.34MB/s]

[syn64882327]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/ISPY2_999733/ISPY2_999733_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.00G/3.00G [09:23<00:00, 5.33MB/s]

[syn64881269]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_01/NACT_01_0000.nii.gz

Downloading files: 100%|█████████▉| 3.01G/3.01G [09:24<00:00, 5.33MB/s]

[syn64882835]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_02/NACT_02_0000.nii.gz

Downloading files: 100%|█████████▉| 3.01G/3.01G [09:24<00:00, 5.33MB/s]

[syn64877793]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_03/NACT_03_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.01G/3.01G [09:24<00:00, 5.33MB/s]

[syn64878584]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_04/NACT_04_0000.nii.gz

Downloading files: 100%|█████████▉| 3.01G/3.01G [09:25<00:00, 5.32MB/s]

[syn64882408]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_06/NACT_06_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.01G/3.01G [09:25<00:00, 5.32MB/s]

[syn64871856]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_07/NACT_07_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.01G/3.01G [09:26<00:00, 5.32MB/s]

[syn64878778]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_08/NACT_08_0000.nii.gz

Downloading files: 100%|█████████▉| 3.01G/3.01G [09:26<00:00, 5.32MB/s]

[syn64880789]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_09/NACT_09_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.01G/3.01G [09:26<00:00, 5.31MB/s]

[syn64878197]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_11/NACT_11_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.02G/3.02G [09:27<00:00, 5.31MB/s]

[syn64872064]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_12/NACT_12_0000.nii.gz

Downloading files: 100%|█████████▉| 3.02G/3.02G [09:28<00:00, 5.31MB/s]

[syn64879960]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_13/NACT_13_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.02G/3.02G [09:29<00:00, 5.30MB/s]

[syn64873409]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_14/NACT_14_0000.nii.gz

Downloading files: 100%|█████████▉| 3.02G/3.02G [09:29<00:00, 5.30MB/s]

[syn64877239]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_15/NACT_15_0000.nii.gz

Downloading files: 100%|█████████▉| 3.02G/3.02G [09:30<00:00, 5.30MB/s]

[syn64879442]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_17/NACT_17_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.02G/3.02G [09:30<00:00, 5.29MB/s]

[syn64876324]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_18/NACT_18_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.02G/3.02G [09:30<00:00, 5.29MB/s]

[syn64880088]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_19/NACT_19_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.02G/3.02G [09:31<00:00, 5.29MB/s]

[syn64872054]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_20/NACT_20_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.02G/3.02G [09:31<00:00, 5.29MB/s]

[syn64872267]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_21/NACT_21_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.02G/3.02G [09:31<00:00, 5.28MB/s]

[syn64874109]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_22/NACT_22_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.02G/3.02G [09:31<00:00, 5.28MB/s]

[syn64882097]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_23/NACT_23_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.02G/3.02G [09:32<00:00, 5.28MB/s]

[syn64871597]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_24/NACT_24_0000.nii.gz

Downloading files: 100%|█████████▉| 3.02G/3.02G [09:33<00:00, 5.27MB/s]

[syn64880659]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_25/NACT_25_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.02G/3.02G [09:33<00:00, 5.27MB/s]

[syn64876483]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_26/NACT_26_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.02G/3.02G [09:33<00:00, 5.27MB/s]

[syn64880744]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_27/NACT_27_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.03G/3.03G [09:34<00:00, 5.27MB/s]

[syn64875047]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_28/NACT_28_0000.nii.gz

Downloading files: 100%|█████████▉| 3.03G/3.03G [09:34<00:00, 5.26MB/s]

[syn64882999]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_29/NACT_29_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.03G/3.03G [09:35<00:00, 5.26MB/s]

[syn64879390]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_30/NACT_30_0000.nii.gz

Downloading files: 100%|█████████▉| 3.03G/3.03G [09:36<00:00, 5.26MB/s]

[syn64873880]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_31/NACT_31_0000.nii.gz

Downloading files: 100%|█████████▉| 3.03G/3.03G [09:37<00:00, 5.26MB/s]

[syn64883715]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_32/NACT_32_0000.nii.gz

Downloading files: 100%|█████████▉| 3.04G/3.04G [09:37<00:00, 5.25MB/s]

[syn64873596]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_33/NACT_33_0000.nii.gz

Downloading files: 100%|█████████▉| 3.04G/3.04G [09:38<00:00, 5.25MB/s]

[syn64878820]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_34/NACT_34_0000.nii.gz

Downloading files: 100%|█████████▉| 3.04G/3.04G [09:38<00:00, 5.25MB/s]

[syn64882460]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_35/NACT_35_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.04G/3.04G [09:39<00:00, 5.25MB/s]

[syn64881743]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_36/NACT_36_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.04G/3.04G [09:39<00:00, 5.24MB/s]

[syn64878179]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_37/NACT_37_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.04G/3.04G [09:40<00:00, 5.24MB/s]

[syn64876808]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_39/NACT_39_0000.nii.gz

Downloading files: 100%|█████████▉| 3.04G/3.04G [09:40<00:00, 5.24MB/s]

[syn64880927]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_40/NACT_40_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.04G/3.04G [09:41<00:00, 5.23MB/s]

[syn64879165]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_41/NACT_41_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.04G/3.04G [09:41<00:00, 5.23MB/s]

[syn64875360]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_42/NACT_42_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.04G/3.04G [09:42<00:00, 5.23MB/s]

[syn64880058]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_43/NACT_43_0000.nii.gz

Downloading files: 100%|█████████▉| 3.04G/3.04G [09:42<00:00, 5.23MB/s]

[syn64875437]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_44/NACT_44_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.05G/3.05G [09:43<00:00, 5.22MB/s]

[syn64883646]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_45/NACT_45_0000.nii.gz

Downloading files: 100%|█████████▉| 3.05G/3.05G [09:43<00:00, 5.22MB/s]

[syn64883206]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_46/NACT_46_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.05G/3.05G [09:43<00:00, 5.22MB/s]

[syn64879474]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_47/NACT_47_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.06G/3.06G [09:45<00:00, 5.23MB/s]

[syn64879363]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_48/NACT_48_0000.nii.gz

Downloading files: 100%|█████████▉| 3.06G/3.06G [09:46<00:00, 5.22MB/s]

[syn64878794]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_49/NACT_49_0000.nii.gz

Downloading files: 100%|█████████▉| 3.06G/3.06G [09:46<00:00, 5.22MB/s]

[syn64881246]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_50/NACT_50_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.06G/3.06G [09:47<00:00, 5.22MB/s]

[syn64880242]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_51/NACT_51_0000.nii.gz

Downloading files: 100%|█████████▉| 3.07G/3.07G [09:47<00:00, 5.22MB/s]

[syn64880395]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_52/NACT_52_0000.nii.gz

Downloading files: 100%|█████████▉| 3.07G/3.07G [09:48<00:00, 5.21MB/s]

[syn64877967]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_53/NACT_53_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.07G/3.07G [09:49<00:00, 5.21MB/s]

[syn64883912]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_54/NACT_54_0000.nii.gz

Downloading files: 100%|█████████▉| 3.07G/3.07G [09:49<00:00, 5.21MB/s]

[syn64874498]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_55/NACT_55_0000.nii.gz

Downloading files: 100%|█████████▉| 3.08G/3.08G [09:50<00:00, 5.21MB/s]

[syn64882745]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_56/NACT_56_0000.nii.gz

Downloading files: 100%|█████████▉| 3.08G/3.08G [09:51<00:00, 5.20MB/s]

[syn64880271]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_57/NACT_57_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.08G/3.08G [09:51<00:00, 5.20MB/s]

[syn64874385]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_58/NACT_58_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.08G/3.08G [09:52<00:00, 5.20MB/s]

[syn64879570]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_59/NACT_59_0000.nii.gz

Downloading files: 100%|█████████▉| 3.08G/3.08G [09:52<00:00, 5.20MB/s]

[syn64874574]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_60/NACT_60_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.08G/3.08G [09:53<00:00, 5.19MB/s]

[syn64877367]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_61/NACT_61_0000.nii.gz

Downloading files: 100%|█████████▉| 3.08G/3.08G [09:53<00:00, 5.19MB/s]

[syn64871606]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_62/NACT_62_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.08G/3.08G [09:54<00:00, 5.19MB/s]

[syn64876441]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_63/NACT_63_0000.nii.gz

Downloading files: 100%|█████████▉| 3.08G/3.08G [09:55<00:00, 5.18MB/s]

[syn64882060]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_64/NACT_64_0000.nii.gz

Downloading files: 100%|█████████▉| 3.09G/3.09G [09:55<00:00, 5.18MB/s]

[syn64874263]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_65/NACT_65_0000.nii.gz

Downloading files: 100%|█████████▉| 3.09G/3.09G [09:56<00:00, 5.18MB/s]

[syn64882641]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_66/NACT_66_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.09G/3.09G [09:56<00:00, 5.18MB/s]

[syn64882377]: Found existing file at /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_67/NACT_67_0000.nii.gz, skipping download.

Downloading files: 100%|█████████▉| 3.09G/3.09G [09:57<00:00, 5.17MB/s]

[syn64873442]: Downloaded to /home/bhkuser/bhklab/katy/jarvais-breast/data/rawdata/BCN-AIM_MAMA-MIA/images/scans/NACT_68/NACT_68_0000.nii.gz

Downloading files: 100%|█████████▉| 3.09G/3.09G [10:05<00:00, 5.10MB/s]